### ISSUE TITLE
SendLeanHelixMessage() always sends as BROADCAST

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#1023]
In `gossip/topic_lean_helix.go`, SendLeanHelixMessage() always sends as BROADCAST even though the caller of this method `leanhelixconsensus/communication.go` SendConsensusMessage() requests to send with `RECIPIENT_LIST_MODE_LIST`.

Also make sure RECIPIENT_LIST_MODE_LIST actually works.

**Comment by electricmonk** [comment]
Make sure the list is the topology rather than the elected validators, otherwise our audit node will not function

**Comment by vistra** [comment]
fixed in #1462
