### ISSUE TITLE
Add NTP to Docker images to fight clock drift

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#1073]
Apparently there's a clock drift (skew) issue with Docker due to virtualization.
We should enable NTP client on our Docker images.

**Comment by netoneko** [comment]
Docker image is the wrong place to do it - containers should run a single process per container. NTP clients should run on the host system.

**Comment by electricmonk** [comment]
@itamararjuan add to Nebula terraform?

**Comment by netoneko** [comment]
We can pass configuration option inside `boyar.json`: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
