### ISSUE TITLE
Code Sanitation does not conform to actual needs

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#1077]
Our contracts are using much more than just the contract SDK, we need to triage and decide on how to resolve - for now turning it off in tests (commit fb4f11071b216dbfa2ade6509a2c3947e5ad5693 and 4cf1993804b7c61d52822e161d89f8fccb79c3a4)

Right now there are two issues to resolve:
- `ORBS_CALC_CONTRACT` for E2E needs `encoding/hex` and `strings`
- the sanitation changes the code, and then the FakeCompiler version which is not sanitized and the version which goes through the processor will mismatch, this will fail acceptance tests (or anything that relies on the FakeCompiler)

**Comment by electricmonk** [comment]
This is mostly in the usability realm, @bolshchikov please decide how to tackle

**Comment by netoneko** [comment]
@jlevison @electricmonk did #1114 address the problem?

**Comment by jlevison** [comment]
activate sanitation in e2e and check, see the commits i referenced (i am not sure it does because of the second bullet)
