### ISSUE TITLE
Timing bug when closing empty blocks in InMemoryTransport

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#1129]
When system runs on idle (closing empty blocks) and a new transaction comes in, it should be processed immediately. 

However, it appears that sending a transaction after the leader already tried to get transactions from txpool and did not find any, causes the full wait time (10m in Gamma) to pass until the next transactions can be closed in a block.

We think this does not happen on mainnet because time to close empty blocks is 10s there so it masks this problem.

**Reproducing this problem:**

Run Gamma with default 10m empty block interval (with lean helix):

On your local machine, go to orbs-network-go and run:
`go run ./bootstrap/gamma/main/main.go -override-config '{"active-consensus-algo":2, "lean-helix-show-debug":true}`

Go to repo gamma-cli and run:
`./_bin/gamma-cli deploy ./test/_counter/contract.go -name Counter`

**Reproducing the "good" case with 10s interval between empty blocks:**

On your local machine, go to orbs-network-go and run:
`go run ./bootstrap/gamma/main/main.go -override-config '{"active-consensus-algo":2, "lean-helix-show-debug":true, "transaction-pool-time-between-empty-blocks": 10s}`

Go to repo gamma-cli and run:
`./_bin/gamma-cli deploy ./test/_counter/contract.go -name Counter`

**Comment by electricmonk** [comment]
reproduced in #1134

**Comment by electricmonk** [comment]
blocked by #950

**Comment by electricmonk** [comment]
fixed in #1134
