### ISSUE TITLE
BlockTracker graceDistance uint16 is too small

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#114]
I changed `graceDistance` from `uint16` to `uint64` and this change was reverted without discussing with me first

The comment now says:
`// this is not primitives.BlockHeight on purpose, to indicate that grace distance should be small`

This is incorrect

We also use `BlockTracker` in tests and in the tests the `graceDistance` should be infinite because we want to wait indefinitely for this block and we can't fail on grace. If the event does not arrive, the test should fail on timeout just like on a deadlock.

Right now, the max value we can put in it is 65K which is too small for the tests. In some tests, the system may close blocks very quickly (empty blocks for example or when we have a single node) so 65K blocks isn't a huge number that can be considered infinite..

The type of this field should be `primitives.BlockHeight` because otherwise you have dozens of unneeded casts all over the place

Delta values are usually the same type of the absolute values. For example unix timestamp is `seconds` from 1970 which is an absolute unit, but we also provide time deltas in `seconds`. It's ok. The fact that it's block height does not mean that it's small or large. It just means that it's measured in block numbers.

**Comment by electricmonk** [comment]
I changed it. I disagree with you - IMO if the tests have to wait for 65K blocks we're doing something very wrong.

I also disagree about the `BlockHeight` type - we should think about what value we get by using the strong types inside implementations. I'm all for strict APIs, but all the casts just to make everything represented by this type seem too much.

Let's discuss after we're back from vacation.

**Comment by electricmonk** [comment]
@talkol let's discuss?

**Comment by electricmonk** [comment]
closing, please reopen if this is still an issue
