### ISSUE TITLE
Config params naming and type conventions are all over the place

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#115]
**Naming mess:**

How many different ways can we phrase time related params?

`QueryGraceTimeoutMillis`
`BlockTransactionReceiptQueryStartGraceSec`
`TransactionExpirationWindowInSeconds`

**Types mess:**

`BlockTransactionReceiptQueryStartGraceSec() time.Duration`
`TransactionExpirationWindowInSeconds() uint32`

**Comment by talkol** [comment]
Requested changes:

1. All time parameters should be able to be provided in a resolution of **milliseconds**. We need this resolution for tests. A test cannot wait a second. This means that fields like `TransactionExpirationWindowInSeconds() uint32` needs to be modified to millis.

2. Choose a single naming convention and change everything to conform.

3. Avoid shortening words just for the sake of making short and thus unclear. For example `QuerySyncGraceBlockDist() uint16` should be `Distance` not `Dist`.

4. All block height related params should be given in `uint64` or `primitives.BlockHeight` which are the type of block height to avoid casting integer types.

5. The minimal integer type should be `uint32`. Putting stuff as `uint16` is problematic for tests. For example `QuerySyncGraceBlockDist() uint16` needs to be set to indefinite in tests and using a value of 65K (max `uint16`) is very far from indefinite when blocks are closing every couple of milliseconds.

6. Choose a single type for time based config and change everything accordingly. After thinking about it some more, `type NodeConfig interface` should ignore all json constrains of simple types.. We should use the type that will avoid as many casts as possible in code. For example `time.Duration` is a better choice than `uint32` for time based events. When we eventually implement `JsonConfig`, we will provide these fields as `number` (probably in milliseconds) and then do the casts inside `JsonConfig`.

**Comment by netoneko** [comment]
Fixed in #133
