### ISSUE TITLE
Transport should be limited to known topology peers

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#1153]
This related to #182 , but comes to fix a more specific problem:

We should limit communication only to known topology at the transport level.

This will address:
1. invalid messages that we receive from non-Orbs entities on the network/VPC - we should only accept connections from known topology
2. limiting at such will reduce the clutter (and potential DoS) from rouge nodes - nodes that are not part of the topology and cannot sync with the network

**Comment by netoneko** [comment]
Unfortunately, I don't think it's possible right now because we only have a single fixed external IP (bound to manager) and can't guarantee that the connection to other nodes will be initiated from there.
