### ISSUE TITLE
Consider syncing clocks between nodes with NTP

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#1158]
**Is your feature request related to a problem? Please describe.**

At present there is no guard against too large a difference between clocks of different nodes and this can result in validation failures of blocks.
The code that validates block timestamps is here:  validate_transactions_blocks.go:isValidBlockTimestamp() for such code.

**Describe the solution you'd like**

Synchronize clocks between nodes, or at least report the clock time as part of /metrics (in Unix millis since epoch format, under "OS.ClockTime") so that monitoring tools (Grafana) can add their alerting layer over this.

**Comment by netoneko** [comment]
I think a good idea would be to utilize something like this: https://github.com/beevik/ntp

We can add a metric to report the clock drift and output warnings in the logs if it exceeds certain threshold and outright shut the node down if has drifted to far.

**Comment by netoneko** [comment]
I believe this is addressed for now, we should only remember to enable it in production configuration.
