### ISSUE TITLE
ethereum connector recovery from a connection failure

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#1160]
**Describe the bug**

The connection object (the client) is 'dialed if needed' only if the object is nil - there is no logic to refresh it if it fails during runtime or if the node changes (dns change) for example.

it is possible that a flow exists where it does recover, but it should be refactored (the dial logic) to be more robust.

**Steps To Reproduce**

1. run the system
2. kill the ethereum node
3. it will not try to reconnect properly

**Expected behavior**

an ability to recover / restart the connection, either manually or periodically.

**Logs**
n/a
**Screenshots**
n/a
**Environment:**
n/a (all)
**Additional context**
n/a

**Comment by electricmonk** [comment]
Oh wow. Is this what I think it is? if so - it's damn serious.
