### ISSUE TITLE
Getting 503 service unavailable if tx is rejected

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1167]
**Describe the bug**

Getting an error `TRANSACTION_STATUS_REJECTED_NODE_OUT_OF_SYNC` with status code `503` instead of `400` (bad request).

```
"error":"transaction rejected: TRANSACTION_STATUS_REJECTED_NODE_OUT_OF_SYNC (expected 2019-05-19 09:25:07.515284919 +0000 UTC but got 2019-05-16 14:42:43.125720143 +0000 UTC)"
```

**Steps To Reproduce**

Send a transactions with an old timestamp.

**Expected behavior**

Get status code `400`.

**Logs**

```
{"entry-point":"PublicApi.SendTransactionAsync","error":"transaction rejected: TRANSACTION_STATUS_REJECTED_NODE_OUT_OF_SYNC (expected 2019-05-19 09:25:07.515284919 +0000 UTC but got 2019-05-16 14:42:43.125720143 +0000 UTC)","flow":"checkpoint","function":"publicapi.(*service).sendTransaction","level":"info","message":"adding transaction to TransactionPool failed","node":"a328846cd5b4979d68a8c58a9bdfeee657b34de7","request-id":"PublicApi.SendTransactionAsync-1558258027515234369","service":"public-api","source":"services/publicapi/send_transaction.go:73","timestamp":"2019-05-19T09:27:07.515401917Z","txHash":"d38a2fa938c4f7db94128c9eebf67c0e8c57cc1d5be043f07b1bdfb8f4642016","vcid":2}
```

**Comment by electricmonk** [comment]
I think this is intentional - `503` means "service is temporarily unavailable"

**Comment by netoneko** [comment]
This bug is related to a race condition in the e2e test: 

1. We start the system with 500 blocks created half a year ago
2. The transaction timestamp is matched with the timestamp of the last block. If the last block was created half a year ago, the node will deem itself as being out of sync.
3. Transaction will be rejected.

**Comment by electricmonk** [comment]
this is a bug, but 503 is still the proper code.
generally a solution would be starting the system with 500 newly created blocks

**Comment by electricmonk** [comment]
TODO: check if after an empty block has been closed, transactions are accepted
