### ISSUE TITLE
when transaction/query execution fails, the errors appear twice in the logs

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#1170]
**Describe the bug**

This creates a lot of 'white noise'
the error comes from both the processor (ProcessCall) and the the publicapi (depends on the endpoint, RunQuery/SendTransaction)

**Steps To Reproduce**

1. create a contract execution error

**Expected behavior**

we should suppress the publicapi (via removing log.Error and replacing it with a different field, so it will not be caught by the error filter)
it is correct for both services to log it, as in the future they might not be monolithic, but the publicapi adds no context, its just information there, the error happens at the processor

alternatively, the idiomatic way may be to not log it at all in the processor, as its an internal component which should not emit logs, just execution results.

**Comment by vistra** [comment]
This seems to only happen in the run-query flow.
I suggest to leave it as is, to avoid the risk of losing the log entirely (in case someone removes the other log in the future).
