### ISSUE TITLE
Add metric for transaction lifespan in pending pool

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1175]
Currently we measure response time from Public API. The drawback is that transactions that were sent via async mode are not measured at all.

I believe that the easiest way to get a good metric in a high volume testing situation would be to create a metric in pending pool that would record the time that transaction has spent in the pool.

This should give us a good measurement of the system's speed.

@gadcl you are welcome to join the discussion.

**Comment by electricmonk** [comment]
There is one:
TransactionPool.PendingPool.TimeSpentInQueue.Millis
