### ISSUE TITLE
WithConfigOverride() in acceptance tests harness should be refactored 

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1209]
Tech debt accrued in https://github.com/orbs-network/orbs-network-go/pull/1168

Neither @ronnno nor @electricmonk want the configuration in tests to be tied to JSON representation, so there is either a need for a builder, or some other option to change config values inside the tests to allow us to explore system limitations and look for optimal configuration values.

The PR itself has provided an option to easily tweakable benchmark for LH consensus that can be used to gain further insight into possible configuration changes and performance optimization.

**Comment by noambergIL** [comment]
fixed during #1596
