### ISSUE TITLE
ResultsBlockHeader in CommitTransactionReceipts is too wide in scope

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#121]
`transactionpool.CommitTransactionReceipts` provides an instance of `ResultsBlockHeader` - out of which transaction pool only needs last block height and timestamp.

This creates unnecessary coupling and provides too wide a scope for transaction pool.

Please introduce changes in proto to *only* pass the block height and timestamp.

**Comment by electricmonk** [comment]
@erankirsh please comment

**Comment by electricmonk** [comment]
@OdedWx @talkol @erankirsh this is still an issue, there's inappropriate intimacy here - txpool shouldn't know the internals of blocks, it only deals with transactions

**Comment by OdedWx** [comment]
It's a corner case, when committing older blocks in block-sync where the transaction pool instance receives blocks with the previous version. May change based on the multi-versions support arch.
