### ISSUE TITLE
Ethereum simulator creating a tech debt

### ISSUE THREAD

**Issue by noambergIL** [orbs-network/orbs-network-go#1214]
Using the ethereum simulator is creating a tech debt. The simulator doesn't have blocks or times (and starts go routines). This means that the ehereum connector has some nasty "newXXwithFake" ctor in service.go, and has some "ignore nil value returned" multiple code.
It also created a possible bug in call method.

possible bug in callmethod: if you give empty block number the expected result is to call method with the newest block AFTER finality. If, for some reason, the finality fails getting block it might return a nil without an error (shouldn't happen and yet) then the function ignores and just goes for latest block WITHOUT finality ! 

look for comments with // note: the geth simulator does not support this API
and ctor NewEthereumCrosschainConnectorWithFakeTimeGetter

consider removing the simulator and moving acceptance test to e2e with ganache.

**Comment by jlevison** [comment]
the simulator is also the reason we cannot update the go-ethereum vendored code.
we are using a very old version (mid-2018). recent versions add support for newer solidity feature (ABI mapping) and already change some go code on our end (see this stale, unmerged commit 9aefc36313f585a83055a972bb7a77371c431ccc , could be that more will need to change other than just that)

there is a bug in the caching engine they use where if you re-run the simulator (between tests) it will leak its cache memory and eventually crash the test runner. they need to change their core.NewBlockChain() to not create a cache when the simulator is calling it, which is irrelevant for the simulator anyways - its as simple as passing a no-cache config to the function..
