### ISSUE TITLE
Do not create separate goroutine when calling LeanHelix.Run

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#1221]
**Describe the bug**
A new goroutine for Lean Helix's MainLoop is presently launched by Orbs. The LH code now launches its own goroutines so Orbs doesn't have to.

See `consensusalgo/leanhelixconsensus/service.go:NewLeanHelixConsensusAlgo` (line 117)

**Comment by electricmonk** [comment]
pre-requisite - extract supervision to own repo, make a dependency of `orbs-network-go`, `boyar` and `lean-helix`

**Comment by electricmonk** [comment]
@IdoZilberberg this is done, right?

**Comment by IdoZilberberg** [comment]
> @IdoZilberberg this is done, right?

@electricmonk yes, done.
