### ISSUE TITLE
Block sync will deadlock if persistence write fails

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#1253]
**Describe the bug**

When a block coming from sync fails to write (but passes validation), lean helix worker will freeze, and then the next time sync runs, sync will deadlock as well

**Steps To Reproduce**

1. Get to a valid sync flow, processing state
2. Fail the write, but make sure validation pass - for the deadlock to happen do not mock anything, LeanHelix is part of the problem
3. Create another sync flow, at the processing stage, validate block before write will deadlock

**Expected behavior**

A write error during sync should gracefully be retried, never mind the logic behind that

**Environment:**

v1.1.1

**Additional context**

The problem is related to how LH works and the current spec
The validate stage of processing will notify the consensus algo

In LH, the notify basically tells the engine that the block is valid, and that LH should now create a new term, that in turn will force LH to get the elected validators, to understand if the current node is participating.
But getting the validators is 'racing' with writing that block, because the block is still being validated and not written yet, as in sync, validation happens before write.

Then back to Orbs, the write fails - back to LH, it is now stuck in an infinite loop trying to get the elected nodes from a block that was not written.
The next time a sync happens to write that block, it will need to be validated before it is written, but the LH worker is busy waiting for the block - meaning the system is deadlocked, sync is stuck, LH is stuck, node is now brain dead.

-> new LH flow has its own context, so this should be fixed on LH side as that context will terminate the LH busy wait when a new sync 'starts' (or new notify happens)

This issue/bug however, is covering the flow from the sync side - question being should it deadlock if LH is acting up, or should it continue to write blocks regardless (LH part is a notification for it to update its internal state, it does not validate / authorize the chain, chain can be healthy without LH, new blocks cannot be written though..)

**Comment by electricmonk** [comment]
@jlevison @IdoZilberberg can you guys please attempt to reproduce this bug in an acceptance test?

**Comment by ronnno** [comment]
see branch `issue/1253`

**Comment by electricmonk** [comment]
@ronnno this should be fixed now, yes?

**Comment by ronnno** [comment]
it is
