### ISSUE TITLE
Run testnet with binaries built with -race flag

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#1260]
Identify data races on the real network, as opposed to running tests with `-race` which will not catch races that don't actually happen during tests.

**Is your feature request related to a problem? Please describe.**
Data races detected in tests of `orbs-network-go` and to a lesser degree in `lean-helix-go`

**Describe the solution you'd like**
Log instances of data races to someplace it can be analyzed, such as logz.io.

See also: https://golang.org/doc/articles/race_detector.html#How_To_Use

**Comment by netoneko** [comment]
It's a great idea. I suggest modifying the build system to include `-race` tag an maybe monitoring for the races from docker stdout from time to time.

**Comment by electricmonk** [comment]
so currently `orbs-network-go` is riddled with races
we need to root out races in dependencies (such as govnr, scribe, etc) and have CI run for these with `-race`
then we can tackle `orbs-netowrk-go`

**Comment by electricmonk** [comment]
so now `orbs-network-go` isn't riddled with races anymore
the question is - do we *need* to run testnet with races? are we worried that there are races we'll miss in CI but catch in runtime?
