### ISSUE TITLE
Understanding Adapter Spaghetti 

### ISSUE THREAD

**Issue by erankirsh** [orbs-network/orbs-network-go#128]
Currently, there's kind of a spaghetti in the implementation of the test harness adapters and the production adapters. 
Specifically, block persistence adapter only implemented in test harness and the production is kept naive and empty. This caused the issue in e2e, what happened was that production adapter implementation was blocking after 10 blocks. e2e in CI was waiting for 5 seconds before starting, so that once it got started, the block persistence was stuck already. Resolved naively in PR #127

**Comment by netoneko** [comment]
This issue was solved in #129

**Comment by jlevison** [comment]
#129 fixed this short term by deleting the 'production' implementation and fixing the issues that made e2e fail. We still need, in both State *and* Block storage to set a standard on how to implement the adapters, at least for now. We should
* discuss how we would like the implementation to be like today (next weekly)
* create the steps to execute the product from that weekly discussion

**Comment by electricmonk** [comment]
IMO this is a discussion we need to have after we’ve implemented at least 80% of state storage and block storage.

**Comment by electricmonk** [comment]
is this still an issue in our opinion?

**Comment by erankirsh** [comment]
Yes. Look at state storage adapter vs block storage adapter implementation

**Comment by electricmonk** [comment]
Block storage has only the testing adapter
State storage has two in memory adapters, one for testing and one for "production"
Not sure we need both of them right now

**Comment by electricmonk** [comment]
closing, reopen if still an issue
