### ISSUE TITLE
Make e2e test run main.go

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#13]
and remember we need one e2e over a docker and one without a docker

**Comment by electricmonk** [comment]
Why do we need an e2e without docker?

Shai
________________________________

**Comment by netoneko** [comment]
We have an option to run e2e against provisioned network, but we need a way to export a specific test file (`e2e_test.go`) as a binary.

**Comment by talkol** [comment]
I'll be happy to run e2e without docker as well just so its faster.. if possible
some times main fails on a stupid mistake and I don't want to wait for full docker build to see it
let's make an effort if this is possible
