### ISSUE TITLE
Flakiness in TestGazillionTxWhileDroppingMessages

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#1312]
```
    panic: timed out waiting for transaction with hash c3f2efee0e0b46009501a466fce590b8df769da857886824e1b1b34b318ffc9c
    
    goroutine panicked at:
    github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/testkit.(*txTracker).waitForTransaction:106
```
https://circleci.com/gh/orbs-network/orbs-network-go/18780#tests/containers/2

**Comment by IdoZilberberg** [comment]
Again: https://circleci.com/gh/orbs-network/orbs-network-go/18853#tests/containers/2

**Comment by electricmonk** [comment]
@ronnno I'm assuming this is related to https://github.com/orbs-network/lean-helix-go/pull/75

**Comment by ronnno** [comment]
Yes. logs confirm it

**Comment by ronnno** [comment]
duplicates orbs-network/lean-helix-go#74
