### ISSUE TITLE
DRY in docker/test/docker-compose.yml 

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#1318]
@electricmonk wrote: https://github.com/orbs-network/orbs-network-go/pull/1303#discussion_r322587156

> this file has become long and repetitive; please see if we can simplify it

**Comment by amir-arad** [comment]
found this:
https://docs.docker.com/compose/extends/

**Comment by itamararjuan** [comment]
Looks cool, although I don't think this is a reason to worry at the moment.
Nobody rarely ever touches this file. but separating it as you say might be a more managable way to represent networks. (as in each compose yml contains only 1 network which is half the services partioned into each file)
