### ISSUE TITLE
Consider getting rid of .version file

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#1326]
**Is your feature request related to a problem? Please describe.**

Presently, the file `.version` must be updated manually when upgrading the version.
This is error-prone.
Instead, use a git tag and automatically generate the file during build.

**Comment by electricmonk** [comment]
@itamararjuan is this done?

**Comment by itamararjuan** [comment]
Yes @electricmonk , already merged to master
