### ISSUE TITLE
Goroutine leak when shipping logs to local ELK stack

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#1352]
**Describe the bug**

Observed on [v1.2.2](https://github.com/orbs-network/orbs-network-go/releases/tag/v1.2.2) 
 (commit `e02d92dc0c`).

The number of goroutines is steadily increasing over time, when log shipping is configured to send logs to our ELK installation on AWS.
It did not happen when logs were configured to be sent to a disk file.
It also did not happen when logs were configured to be sent to logz.io (a hosted ELK solution we use with mainnet).

Some links:
[Grafana](http://ec2-34-222-245-15.us-west-2.compute.amazonaws.com:3000/d/a-3pW-3mk/summary?refresh=10s&panelId=40&orgId=1&from=1569433511253&to=1569644574110&fullscreen&edit) view that shows the symptom.

[Metrics](http://52.204.239.242/vchains/2013/metrics) for one of the testnet's nodes
The relevant goroutine metric is `Runtime.NumGoroutine.Number ` - perhaps other metrics such as TCP connections can be useful.
The metrics dump shows the present state of the node, so it will not show the problem. I added it here for completeness because this is where Grafana gets its data from.

The ELK installation is [this](https://github.com/deviantony/docker-elk) - we installed it on AWS.

**Steps To Reproduce**

Don't do this one alone - ask someone to help (@itamararjuan or @IdoZilberberg)

The log shipping for testnet is configured by changing the Boyar config file, and updating it on AWS S3. The update to S3 triggers a restart of the nodes (the nodes periodically check the config file for changes, and restart if a change is detected).

Test config can be found [here](https://github.com/orbs-network/testnet-configuration/blob/master/marvinnet/config.json), under chains->2013.

* To ship logs to ELK (the one that causes the problem), add new property:
`"logger-http-endpoint": "http://ec2-34-222-245-15.us-west-2.compute.amazonaws.com:9200",`

* To ship logs to logz.io (the one we use for production, doesn't show the problem), add new property:
`"logger-http-endpoint": "https://listener.logz.io:8071/?token=kATbDvYGTXTOOfyvDYGbWrGdIFBPpvHI&type=prod",`
under `"ethereum-finality-blocks-component"`

* To ship logs to local file (default): remove the property `"logger-http-endpoint"` 

**Expected behavior**

Goroutines should fluctuate within a constant range, and not increase over time (40-50 per node is normal, with occasional higher spikes which quickly go down back to 40).
We use [Grafana](http://ec2-34-222-245-15.us-west-2.compute.amazonaws.com:3000/d/a-3pW-3mk/summary?refresh=10s&panelId=40&orgId=1&from=1569433511253&to=1569644574110) to monitor goroutines and all other metrics over time.

**Screenshots**

![image](https://user-images.githubusercontent.com/10131768/66021961-0e53bc80-e4f5-11e9-91b0-bf402ada2566.png)

**Comment by netoneko** [comment]
https://github.com/orbs-network/scribe/issues/11

**Comment by vistra** [comment]
The actual logging endpoint that caused the issue is http://ec2-34-222-245-15.us-west-2.compute.amazonaws.com:5000 (logstash),
 and not http://ec2-34-222-245-15.us-west-2.compute.amazonaws.com:9200 (elasticsearch).
The logstash endpoint is _not_ an HTTP endpoint, its a raw TCP server expecting an endless stream of log records separated by line-breaks. It doesn't respond with any data.
Log shipping still worked despite being treated as HTTP, because HTTP is textual as well, and one line from the HTTP request contained the JSON of the log record. 
However since logstash never responds, and the default HTTP client in Go is never times-out, the connection (and the corresponding goroutine, created for each request) remain open forever.

**Comment by electricmonk** [comment]
@vistra did you end up fixing Scribe?
