### ISSUE TITLE
Triggers transactions always fails because of missing signer

### ISSUE THREAD

**Issue by noambergIL** [orbs-network/orbs-network-go#1355]
**Describe the bug**

Trigger has check inside the contract code for empty signer, However sdk fails if signer is empty (sdk doesn't know its trigger).

Short term : remove the check from _Trigger.trigger
Long term: add a schema ? add node signature to the tx ?

**Reproduce*
(look for in log for "result=EXECUTION_RESULT_ERROR_SMART_CONTRACT error=transaction is not signed by any Signer transaction-or-query" in any acceptance or e2e but make sure config is set to trigger on

**Comment by electricmonk** [comment]
we decided to add a hard-coded sender address for trigger txs
