### ISSUE TITLE
Flakiness log write after shut down

### ISSUE THREAD

**Issue by noambergIL** [orbs-network/orbs-network-go#1360]
https://circleci.com/gh/orbs-network/orbs-network-go/19829?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

TestTicksOnSchedule

*** Logged error after TestOutput.TestTerminated: TestTicksOnSchedule : error 2019-10-03T11:50:36.493401Z recovered panic error=Forever governed goroutine  cleaner trigger timed out while waiting for shutdown: context deadline exceeded panic=true stack-trace=goroutine 35 [running]:
runtime/debug.Stack(0x8e6380, 0xc000226090, 0xc0001fcd90)

**Comment by electricmonk** [comment]
assuming this was caused by old Scribe version, reopen if recurs
