### ISSUE TITLE
Metrics - committee members

### ISSUE THREAD

**Issue by gadcl** [orbs-network/orbs-network-go#1379]
Add current committee members info to metrics  (count ..)

**Comment by netoneko** [comment]
This is why I have suggested that the reputation contract should store history - then we can go back in time a get the committee for a specific block, etc.

**Comment by electricmonk** [comment]
we're emitting events, which is the best type of history IMO. Anything else is an aggregate and can be generated from the events. The metric is different IMO - @gadcl can you please indicate *why* you want this metric?

**Comment by gadcl** [comment]
Feedback from Oren about the node's metrics (url) readability - where investigating the node's metrics it lacks this reference context leaving the metrics meaning vague. 
If there is a need to expose block committee members we can discuss it - but I dont see how it relates to the subject at hand

**Comment by electricmonk** [comment]
Guidance: the code that creates the committee is in `consensuscontext.RequestValidationCommittee`
