### ISSUE TITLE
Make the buffer size for reading the block file reader configurable

### ISSUE THREAD

**Issue by vistra** [orbs-network/orbs-network-go#1382]
We use a buffered reader to read the block file efficiently. Currently the buffer size is hardcoded to 1MB, although the optimal size is highly dependent on hardware, network, etc.

The buffer size is defined at `file_system_persistence.go: NewBlockPersistence()`

**Comment by electricmonk** [comment]
I wanna say YAGNI, convince me I'm wrong

**Comment by electricmonk** [comment]
I think YAGNI

**Comment by vistra** [comment]
Will anyone want to experiment with the buffer size in production? If so,
would making it configurable make it easier?

**Comment by netoneko** [comment]
I'd say YAGNI, if we hit the problem one more time, we might go in that direction.

**Comment by ronnno** [comment]
voted YAGNI
