### ISSUE TITLE
Contract compilation is killed prematurely

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1387]
I observe that sometimes a contract fails to compile with the following error:

```
could not build a shared object: error building go source: signal: killed, go build output: 
```

Instead of fixing the issue, the tests have a workaround that just keeps querying the contract until it succeeds.

Relevant builds: https://circleci.com/gh/orbs-network/orbs-network-go/20511

**Comment by electricmonk** [comment]
can you please attach a log snippet with the issue?

**Comment by netoneko** [comment]
Here are all the relevant logs: https://circleci.com/gh/orbs-network/orbs-network-go/20529#artifacts/containers/0

**Comment by electricmonk** [comment]
to the description, please
I want people who view this issue to see the error you posted above in context
