### ISSUE TITLE
Consistently timeout is too long for some tests

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#140]
The running time for `benchmarkconsensus/test` has increased from 200 ms to 2 sec

I can only assume it's because the new value for consistently that was needed for e2e

I think there's no choice and we must have slow tests and fast tests and have different timeouts for both. One way to implement this is to use `t.Short()` to check if we have a fast run or a slow run.. Not a very good solution though

Another option is to have some configuration that the e2e will set that will change a global variable for the duration of this test.. but this sucks because it will leak between tests.. maybe save this parameter on `t` somehow

**Comment by electricmonk** [comment]
is this still an issue?

**Comment by talkol** [comment]
@erankirsh bump
yes, this is still an issue

tests that were 50ms today have before 500ms, we increased the consistently factor x10 and it's only needed for e2e

**Comment by talkol** [comment]
Example test I'm working on right now where this is an issue:

`TestIncoming_TransportListenerDoesNotReceiveCorruptData_NumPayloads`

A consistently value of 50ms in this test should be enough

**Comment by electricmonk** [comment]
Any reason not to 'overload' with a `ConsistentlyFor(duration time.Duration)` function?
