### ISSUE TITLE
RunQuery denial of service

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1438]
**Describe the bug**

A specially crafted message can cause denial of service.

**Steps To Reproduce**

Send a query with BlockHeight parameter set to something other than 0.

**Expected behavior**

No denial of service should occur.

**Additional context**

https://github.com/orbs-network/orbs-network-go/blob/09453950f16a62fcc1ddf16543496d8a976ab8fa/services/virtualmachine/service.go#L59

**Comment by electricmonk** [comment]
@netoneko can you please elaborate how you suspect this would result in denial of service?
Regardless, I think this panic is bad design, we shouldn't have included this parameter in the message .proto file if we didn't intend to support querying by block heihgt
