### ISSUE TITLE
Logger could be better

### ISSUE THREAD

**Issue by itamararjuan** [orbs-network/orbs-network-go#144]
The logger has a few issues IMO:
- log.GetLogger() suggests the singleton pattern although it is actually a constructor
- Having too many logger instances floating around is costly and also unmanageable in terms of silent/verbose operation
- Possible memory issue with too many logger instances
- Ability to track down a transaction or method invocation on the log is currently very hard
- Need to debate which directions are possible to allow more control over logging in general through-out the life cycle of the process.

**Comment by electricmonk** [comment]
@itamararjuan please discuss your concerns with @netoneko
