### ISSUE TITLE
System froze(??) for 1 second in acceptance tests running on CircleCI

### ISSUE THREAD

**Issue by vistra** [orbs-network/orbs-network-go#1443]
https://circleci.com/gh/orbs-network/orbs-network-go/22005#tests/containers/2

There were no log records between 23:13:41.668338 and 23:13:42.695971. 
It failed the test because getOrderedCommittee hit a timeout, which caused an error to be logged.

Update 12/11 - happened again with the same test
https://circleci.com/gh/orbs-network/orbs-network-go/22322#tests/containers/1
~500ms freeze starting at 23:11:00.834153
No heartbeats were printed to the log during that period

**Comment by electricmonk** [comment]
another heartbeat mechanism we might employ here is a background job at the OS level that prints current date, running in parallel to the `go test` process

**Comment by vistra** [comment]
Maybe also print cpu/memory usage with each heartbeat

**Comment by electricmonk** [comment]
it's gonna be a vcpu though, so it's not going to be indicative of anything really
