### ISSUE TITLE
Add acceptance test for a node starting with blocks already in persistence

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#145]
This might be a huge amount of work considering consensus does not accept it.

**Comment by electricmonk** [comment]
It would mean getting a harness to a stopped node, writing blocks to storage, then starting it.

Shai
________________________________

**Comment by electricmonk** [comment]
@netoneko @jlevison is this something you took care of for the Block Sync acceptance test?

**Comment by electricmonk** [comment]
I think so, closing
