### ISSUE TITLE
harnesss.WaitUntilTransactionPoolIsReady prevents running e2e tests against gamma

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1457]
**Describe the bug**

Running e2e tests against gamma fails because of the timeout error:

```
Messages:   	timed out waiting for a transaction pool to sync a recent block and begin accepting new tx
```

**Steps To Reproduce**

Run e2e tests against gamma

**Expected behavior**

E2E tests against gamma should pass

**Additional context**

The problem is that we assume the speed with which the block height increments. In local gamma, it takes 10m to create another block, not 1-5 seconds.

To mitigate this issue, I propose we add an environment variable that disables the check.

**Comment by electricmonk** [comment]
I already closed such an issue (#1431) earlier this week. In my opinion running E2Es against Gamma isn't a requirement. @netoneko can you please elaborate why this is needed in your opinion?

**Comment by netoneko** [comment]
@electricmonk I believe it is needed to prove that gamma works the same way as regular network.

**Comment by electricmonk** [comment]
We have acceptance tests that run on code shared between Gamma and the production node
The difference between them is isolated to bootstrapping and composition concerns (storage, communications, etc), each tested in contract tests between production and test adapters. We have an E2E that proves that Gamma can start and close blocks, and we have an E2E that starts a Gamma docker container to prove that docker build yields a valid container.

Do you think we're missing anything?
