### ISSUE TITLE
Can't kill node process with ^C

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1460]
**Describe the bug**

Can't kill node process with ^C if started on a local machine.

**Steps To Reproduce**
```
go run ./main.go --config ./docker/test/benchmark-config/node1.json --config ./docker/test/benchmark-config/node1.keys.json
```

**Expected behavior**

Should be able to stop the node by pressing ^C

**Additional context**

It's useful for local debugging.

**Comment by electricmonk** [comment]
It's interesting because we're supposed to support this. Time to write a unit test for https://github.com/orbs-network/orbs-network-go/blob/master/synchronization/supervised/shutdown.go

**Comment by electricmonk** [comment]
@netoneko do you see the message "terminating node gracefully due to os signal received" in the log after hitting ctrl+c?

**Comment by electricmonk** [comment]
works for me, takes 10 seconds or so to shutdown after hitting ctrl+c

**Comment by amir-arad** [comment]
works for me
