### ISSUE TITLE
Declutter block sync logs

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#1479]
BlockSync emits a lot of info-error logs, for instance:
> HandleBlockAvailabilityRequest failed unknown recipient public key: 0c4e040fb7991f6aeb96e25708bf5a366d66c925

This is noise, but if this sort of issue happens often it might be indicative of an issue with sync in general.

Consider removing the error object from all info logs in block sync (thus removing them from logz.io), and instead add an error that gets emitted if a node didn't get a block (via sync or via consensus) for more than _k_ seconds / minutes.

**Comment by netoneko** [comment]
This particular is not noise at all and helps with debugging production configuration issues. It was added there for a reason.

Unless an alternative is introduced fist, this message shouldn't be removed because it affect ability to debug system as a whole.

**Comment by netoneko** [comment]
BlockSync was already rewritten several times, any log issues should be addressed as a separate cleanup effort
