### ISSUE TITLE
Tagged metrics

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1485]
Currently we already tag metrics with certain things (node address, virtual chain id).

I propose we add a method to the `MetricRegistry` that allows you to tag metrics in a generic way.

Example: per-connection latency metrics. It would be better to have 

`Gossip_OutgoingConnection_Latency{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",aggregation="95p",recipient="cb6fc0fd54c2b2eb1b75f855d5f2f401742568b"} 0.000303`

as opposed to current

`Gossip_OutgoingConnection_Latency_cb6fc0fd54c2b2eb1b75f855d5f2f401742568b{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",aggregation="95p"} 0.000303`

Related PR: #1484

**Comment by electricmonk** [comment]
We also have the same issues for client send errors, also in gossip.
Making this possible would require a significant change in the metric system. I know that @owlen had some reservations with regards to how the metric system is currently implemented, so let's make sure that any suggested change is aligned with the general direction of things.

**Comment by netoneko** [comment]
This is not a significant change at all. It would require to add one method and a slice of strings to store labels:

https://github.com/orbs-network/orbs-network-go/blob/197b2b027af09e15e1aea33d67b6b76322ca8661/instrumentation/metric/registry.go#L232

**Comment by electricmonk** [comment]
the metric registry currently maps metrics by their name; if we use the same name for multiple metrics, it would require changing how we hold metrics.
