### ISSUE TITLE
Issues with gossip latency metric

### ISSUE THREAD

**Issue by vistra** [orbs-network/orbs-network-go#1486]
#1484 added a peer based latency metric, there seems to be two issues there (not verified):
1. The metric is updated only on keep alive messages, which only transmit when the connection to the peer is silent. Effectively this means that most of the time the metric will not be reported.
2. The latency is measured by timing the `write()` call on the connection. This call will most likley return immediately as the OS uses internal buffering. See https://stackoverflow.com/questions/5407182/blocking-sockets-when-exactly-does-send-return and https://stackoverflow.com/questions/53248807/golang-socket-doesnt-send-all-bytes-before-write-method-returns

@netoneko @electricmonk @IdoZilberberg

**Comment by netoneko** [comment]
1. The metric will be reported because we send keep-alive all the time. The queue drains eventually.

2. If this is the case, we might want to add a keepalive response and measure the time until we got it.

**Comment by electricmonk** [comment]
@netoneko - keep alive message do not get fired unless there's no communication for over 1 second

**Comment by electricmonk** [comment]
#1488 reverted this change. @gadcl if you still think this is a valuable metric, we'll need to spend some time fixing the keepalive mechanism to support this
