### ISSUE TITLE
Refactor comparison of blocks in block storage

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#149]
https://github.com/orbs-network/orbs-spec/pull/71

**Comment by talkol** [comment]
Notice that we changed the spec and now you only need to compare the bytes of the Transactions block header and Results block header. No need to compare the bodies, it's expensive and redundant.

**Comment by electricmonk** [comment]
is this still an issue? if so - we have an `Equal` method for each domain object, right? can we use it?

**Comment by netoneko** [comment]
Fixed in 9016305
