### ISSUE TITLE
Don't build binaries inside docker

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#1493]
Today our build system creates a container named `orbs:build` and builds the binaries inside it. 
This is done so that we can compile linux binaries, regardless the OS the build runs on.

However, it slows down the builds and make it harder to understand what's going on.
Instead, use `GOOS` and `GOARCH` environment variables:
https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04

**Comment by abi1296** [comment]
Hi,
  I am new to this orbs-network. I am trying to setup the orbs-network using this repo. But when I tried to do it with the docker environment, I could find the file "build.sh".
 So I tried the other way "build from source", I ran the command "go get github.com/orbs-network/orbs-network-go" but I am getting the error as
"#github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp
 src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/outgoing_connection.go:77:11: cannot use handle.Done() (type govnr.ContextEndedChan) as type chan struct {} in assignment".
P.S: OS: ubuntu version -18.04
 and go version : go version go1.10.4 linux/amd64

Could you please help me?


Thanks in advance.

**Comment by netoneko** [comment]
Not relevant.
