### ISSUE TITLE
flakiness TestServiceBlockSync_StateStorage

### ISSUE THREAD

**Issue by amir-arad** [orbs-network/orbs-network-go#1497]
(log too long)
https://circleci.com/gh/orbs-network/orbs-network-go/23520#tests/containers/1

failed:
 - TestServiceBlockSync_StateStorage - acceptance
 - TestServiceBlockSync_StateStorage/CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS - acceptance

**Comment by noambergIL** [comment]
not happen in 5 months closing
