### ISSUE TITLE
consider increasing grace for signer of first block

### ISSUE THREAD

**Issue by amir-arad** [orbs-network/orbs-network-go#1498]
Boyar e2e tests with external signer sometimes fail with "leader failed to sign genesis block" message:
```
leader failed to sign genesis block node=a328846cd5b4979d68a8c58a9bdfeee657b34de7 service=consensus-algo-benchmark vcid=42 error=error sending request to signer server: Post http://node1-signer-service-stack:7777/sign: dial tcp: lookup node1-signer-service-stack on 127.0.0.11:53: no such host function=benchmarkconsensus.(*Service).leaderGenerateGenesisBlock source=/src/services/consensusalgo/benchmarkconsensus/leader.go:120 
```
perhaps on bootstrap scenarios (namely `leaderGenerateGenesisBlock` method) we should add some retries to let other services time to start themselves?

**Comment by netoneko** [comment]
Some joint investigation with @amir-arad revealed that the problem originates in the benchmark consensus, so it's not a production issue.

**Comment by noambergIL** [comment]
closing as 1) signer moved, 2) benchmark and seems less relevant now.
