### ISSUE TITLE
Public API returns 501 when looking for TxStatus of an unknown tx

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#1499]
**Describe the bug**

Spec specifies that the mapping between `TRANSACTION_STATUS_NO_RECORD_FOUND` to http code should be `http.StatusNotFound`, but it translates to `http.StatusNotImplemented`

test to reproduce the issue created in branch `bugfix/missing-get-tx-status` by @netoneko 

**Steps To Reproduce**
execute `TestGetTxStatus` e2e test

**Comment by netoneko** [comment]
Guys, it's been almost two weeks since the bug was uncovered. @electricmonk please prioritize. It's a developer experience issue.

**Comment by netoneko** [comment]
There needs to be a fix also on the client (the test of the fix depends on returning an error which is wrong behaviour; if we already have a status object, the errors are reserved for the transport layer only).

I will send another PR after the client is patched to update the test.
