### ISSUE TITLE
Updating default configuration for TRANSACTION_EXPIRATION_WINDOW

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1503]
I propose an update for `TRANSACTION_EXPIRATION_WINDOW` from current value of `30m` to `60m`.

The reason: sometimes it takes a network a long time to recover from the reload, so some transactions might be lost when resubmitted or expire while already in the pool.

**Comment by gadcl** [comment]
in v2 network upgrades are more robust and circumvent this issue; each node upgrades in the span of 24h (randomly) - avoiding too many nodes upgrading at once (which extends the time it takes to recover\sync quorum to the same view)
