### ISSUE TITLE
BlockSync - a node too far behind may stop syncing forever

### ISSUE THREAD

**Issue by vistra** [orbs-network/orbs-network-go#1514]
A block sync request asks for a range of blocks, of a size defined in the node configuration.  If the chunk size (in bytes) is larger than the transport queue size (currently 20mb), the transmission of the chunk is guaranteed to fail. 

The chunk size configuration is defined by number of blocks per chunk, not by number of bytes. So the chunk size in bytes may vary significantly depending of the size of the blocks in the range. 

If the configuration allows, a node too far behind may ask for a chunk too-large to fit the send queue buffer, and the sync will never advance.

root cause of #1511

**Comment by electricmonk** [comment]
After a discussion with @OdedWx, we suggest the following:
1) Chunk size configuration is a recommendation, or can be cancelled completely
2) Each petitioner asks for the maximum number of blocks it needs, or it can be capped by chunk size
3) The server further limits the transmission size given a hard limit (not configurable) that is derived from the TCP transport layer via the gossip service

**Comment by electricmonk** [comment]
This is actually more difficult than it seems -
The transmission size is a `gossip` limitation. If we respect the context boundaries, `block-storage` shouldn't care about this. So we either have to add another function `gossip.GetMaxMessageSizeInBytes`, or we allow `gossip/topic_block_sync` to tamper with the message, reducing the block content until it falls under the hard limit. Neither is pretty.

**Comment by vistra** [comment]
Another option is to have the block-storage itself cut the message in half
and retry iteratively on each failure. But I vote for the gossip.
GetMaxMessageSizeInBytes option.

**Comment by netoneko** [comment]
We already had this problem in production, is there any timeline for the fix?

**Comment by electricmonk** [comment]
for now just set chunk size to a lower value, please

**Comment by netoneko** [comment]
@electricmonk can we at least get a configurable queue size? 20Mb per connection seems quite underwhelming.

**Comment by ronnno** [comment]
tcp transport did not return the expected error - causing this fix to not be activated in production
