### ISSUE TITLE
Experiment with github.com/valyala/fasthttp as alternative to standard HTTP server

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#152]
**Pros of standard HTTP server (existing):**
* no dependencies (security)
* official

**Pros of alternative:** https://github.com/valyala/fasthttp
* improved performance

**Comment by electricmonk** [comment]
Improved over what? are we going to have a bottleneck with the standard library?

**Comment by talkol** [comment]
It's not in the critical path, a good task for an external contributor.
To compare both implementations.

**Comment by electricmonk** [comment]
but is it even something we want to do? we will increase accidental complexity without clear benefits

**Comment by yonidavidson** [comment]
I want to implement the server.go with fast http and compare stress tests on it against the original version. does it sound like a good comparison?

**Comment by talkol** [comment]
@yonidavidson I think it's a cool task. I wouldn't replace the existing `server.go`, just create a new one called `fasthttp_server.go` next to it

**Comment by yonidavidson** [comment]
So I am working on this here https://github.com/yonidavidson/orbs-network-go/pull/1/files
I need to debug and understand why it doesn't work.

**Comment by electricmonk** [comment]
Closing for now, we'll come back to this if there's ever evidence for performance issues with HTTP
