### ISSUE TITLE
Consider adding a cap on the size of state variables

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#1524]
We experienced very bad memory behavior when a single state variable is very big (e.g. 50MB)
depending on the contract, today it is rather simple to DOS the vchain or even in a non-malicious way write contracts which will make the virtual chain unstable.

we should consider to limit state variables to several MB (<10)

**Comment by electricmonk** [comment]
This is a protocol change. Can you please move to https://github.com/orbs-network/orbs-spec and ping @OdedWx ?
