### ISSUE TITLE
Startup errors are swallowed

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1535]
It seems like production image fails when `genesis-validators` config row is empty, however, no errors are displayed in the log.

**Comment by Keerthana-Jayakumaran** [comment]
Hi netoneko,         
I hope you have setup the orbs network already. I am trying to do the same. But when i tried to do with the docker environment, I could find the file "build.sh".
So I tried the other way "build from source", I ran the command "go get github.com/orbs-network/orbs-network-go" but I am getting the error as 

**_"#github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp
src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/outgoing_connection.go:77:11: cannot use handle.Done() (type govnr.ContextEndedChan) as type chan struct {} in assignment"._**

P.S: OS: ubuntu version -16.04
and go version : go version go1.13.8 linux/amd64
 


Could you please help me?

Thanks in advance.

**Comment by netoneko** [comment]
@Keerthana-Jayakumaran the docs are a bit outdated.

To build the node from source you could use `./build-node.sh`

To build local dev environment: `./build-gamma.sh`

Also see #1536

**Comment by Keerthana-Jayakumaran** [comment]
Thanks @netoneko
