### ISSUE TITLE
Cannot able to find build.sh file to run this repo using docker images?

### ISSUE THREAD

**Issue by abi1296** [orbs-network/orbs-network-go#1536]
In your documentation (Readme.md), under "**Building Docker images only**" title you mentioned to use **Run ./docker/build/build.sh to create the images:** this step. 

But this **build.sh** file is not found under this **docker/build** folder when I cloned this repository. 
Can anyone help me to solve this issue?

**Comment by netoneko** [comment]
You are correct. We should've update the docs.

For building the node: `./docker/build/build-docker-node.sh`

For building gamma (local dev environment): `./docker/build/build-gamma.sh`

**Comment by abi1296** [comment]
> You are correct. We should've update the docs.
> 
> For building the node: `./docker/build/build-docker-node.sh`
> 
> For building gamma (local dev environment): `./docker/build/build-gamma.sh`

thanks for your reply.
