### ISSUE TITLE
release-gamma-test fails 

### ISSUE THREAD

**Issue by gadcl** [orbs-network/orbs-network-go#1646]
running on circle ci tests - release-gamma - fails on  Pulling from orbs-network-gamma
for example https://app.circleci.com/pipelines/github/orbs-network/orbs-network-go/511/workflows/5e96e2ab-a95c-4c3a-a868-1e8d3521153f/jobs/30557

**Comment by noambergIL** [comment]
another example https://app.circleci.com/pipelines/github/orbs-network/orbs-network-go/576/workflows/c5395ab6-3ef9-4f8b-bd25-b85ff2923efa/jobs/30783

https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
9aff5675: Pulling from orbs-network-gamma

a430b2ba: Pulling fs layer 
acb629f5: Pulling fs layer 
8c8d4f9a: Pulling fs layer 
eaa7dd42: Pulling fs layer 
197e145e: Pulling fs layer 
f3af643f: Pulling fs layer 
ef9877e3: Pulling fs layer 
7fbde1a3: Pulling fs layer 
914af6c3: Pulling fs layer 
15b9c211: Pulling fs layer 
Digest: sha256:2b3851a8304bc72affd889820bb87492fe5ee538a772efd550d88e259c28903c
Status: Downloaded newer image for ***************************************************************:9aff5675
The push refers to repository [docker.io/orbsnetwork/gamma]

2a077e33: Preparing 
e80c459c: Preparing 
93830b86: Preparing 
a40846f4: Preparing 
7e73ef79: Preparing 
c8f1e717: Preparing 
718a7d23: Preparing 
27feeccb: Preparing 
1895156d: Preparing 
a9daa22c: Preparing 
denied: requested access to the resource is denied

Exited with code exit status 1
CircleCI received exit code 1

**Comment by netoneko** [comment]
The problem occurred because some permissions were revoked, I have reinstated them only to release gamma automatically.
