### ISSUE TITLE
Configuration is still a mess

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#167]
Please input all of your requirements from the config under this issue, hopefully somebody will plan a better configuration mechanism

**Comment by talkol** [comment]
* Support different configurations from different block heights

* Allow to instantiate a minimal configuration for a service/adapter that only has its own fields without providing unneeded fields there

* Have defaults for all values and allow to change every field to a new value

**Comment by netoneko** [comment]
2) is done through calling `config.EmptyConfig()` and setting relevant values in the harness

3) is already there

**Comment by electricmonk** [comment]
> Support different configurations from different block heights 
@talkol do we need this for V1?

**Comment by electricmonk** [comment]
Closing for now
