### ISSUE TITLE
Improving dev experience for debugging logs for tests like e2e

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#171]
Imagine e2e is failing..
It's a test running for ~2 seconds which is generating about 10MB of logs..
You're trying to go over the logs to understand what's wrong..
You're not going to have a good time.

A proposal on how to improve this:

1. Add another log level in reporting, so now we'll have `Error`, `Info` and `Important` (think of a better name than Important, let's assume it's like Info just more important). All important events should be logged under `Important`.

2. To make sure that people don't abuse `Important` - create an e2e test that does nothing for 1 second - it just let's the system run idle and close empty blocks. If any of the logs in this test are `Important` - the test will fail. This will make sure none of the idle state logs are considered important.

3. The steps of debugging a huge log file is:

    1. Grep for `log.Error` to see if we have any real errors - if you found an error, yay. If not, continue..

    2. Grep for `log.Important` and see if you understand what's going on. This should be significantly less than 10 MB.

    3. If you need a little context around these events, grep for `log.Important` while showing 10 lines before and 10 lines after each `log.Important` (using grep -A -B).

    4. If all this doesn't help, you have no choice and must debug the actual logs.

5. Also - I propose to write the log of every node (docker instance) to a different file and go over them separately. Our real e2e's will run with something like 22 nodes. There's no way we can go over a log that merges all of them.

**Comment by electricmonk** [comment]
+1 for @jlevison. Going over logs like this is not a viable way to debug production (or e2e test) issues. The logging system must be searchable and filterable, and ideally allow us to visualize the flow.

@talkol can you please formalize how you'd like the debug experience to be? we will derive the technical solution after we've defined the product requirements.

**Comment by talkol** [comment]
@electricmonk I'll do my best to give my "requirements" for debugging logs (tests that output lots of logs and I'm trying to investigate what's the issue in them):

1. Do it inside the IDE. I usually run the tests inside the IDE and I'd like the solution to be integrated as much as possible to IntelliJ. For example, if grepping becomes an important part of the log debugging process, we need some grepping plugin for IntelliJ.

2. Identify errors quickly. We have a log level for errors, this is the first thing that should jump to me.

3. Be able to track a transaction. We do this a lot. I want to see all the places that this transaction traveled to. All the log lines related to it: It was received by public-api here, then it was added to transaction-pool here, then it was added to a block here..

4. Be able to reduce noise automatically from the log. We can define noise like this - find the 20 least frequent log messages and only display them.

5. Be able to focus (filter) on a specific service (ie. just transaction-pool) or a specific node. This could be done by grepping.

6. If a test is stuck on some line (blocking endlessly) and the test ternminates on a timeout - I want to be able to see which line we were stuck on.

**Comment by talkol** [comment]
I think this plugin may be a way to implement all of the above:

https://plugins.jetbrains.com/plugin/7125-grep-console

It support scripts too! `Change output or execute any action using custom groovy scripts or plugins.`

I can implement my noise remover as a script in 10 minutes!

**Comment by talkol** [comment]
Re: 4 - not sure they are garbage.. it all depends on the context you're looking at. For example, in a long test where I send one transaction, logging of empty blocks that are closed are "garbage"

But if I want to verify liveness (that the algorithm isn't stuck) or research why there's no liveness anymore, then these empty blocks closed are important

**Comment by electricmonk** [comment]
I believe #404 helps mitigate this so I'm closing
