### ISSUE TITLE
functionality missing in block sync

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#174]
1. chuncking
2. not waiting 8 seconds before next batch starts
3. all the message should have signatures on them (check the signature / sign the message)
4. timeouts for operations - waiting for block sync response

**Comment by talkol** [comment]
intra node block sync

**Comment by electricmonk** [comment]
@jlevison please update status and/or close the issue

**Comment by electricmonk** [comment]
@OdedWx do we want to work on any of this during Q32019?

**Comment by OdedWx** [comment]
Signing should be fixed (not the full messages) will align the spec.
As for improved batching / OOO, currently not high priority, handing the sync time of a "brand new" validator will be managed as part of the elections flow.

**Comment by electricmonk** [comment]
@gadcl  @ronnno we saw that a new validator took 16 hours to sync. Do you think it's worth to change the behavior so that we don't wait 8 seconds before requesting the next chunk?

**Comment by gadcl** [comment]
I think @avilanthe1 is investigating the syncing process. Optimization approaches might include for example, syncing only the blockchain tip to start participating in the consensus and syncing the rest in the background, syncing blockchain partitions in parallel.

**Comment by electricmonk** [comment]
As per my conversation with @gadcl, I'd like to make a change so that from Processing Blocks state we go back to Broadcasting Availability Request, saving 8 seconds on each chunk.

This should speed up full syncs at the cost of adding more noise to nodes that just fell slightly behind, or the audit node.

To mitigate that, we might add a heuristic to only go back to Broadcasting state if we processed a full chunk size (as opposed to one or two blocks)

**Comment by electricmonk** [comment]
@amir-arad let's do this one together

**Comment by netoneko** [comment]
The block size is around 2.5Kb. The default chunk size is 100, making it 250k per transfer.

Just set the chunk size to 100000 (= 25Mb per transfer) and the syncing problem will go away.

**Comment by netoneko** [comment]
It would be much more useful to count the size of blocks and put a limit on that (no more than 50Mb or 100Mb chunks, for example) without putting emphasis on the number of blocks.

@OdedWx what do you think?

**Comment by electricmonk** [comment]
@ronnno what mismatch from the spec are you referring to?

**Comment by ronnno** [comment]
Spec sais: `Synchronization is made of multiple batches, each comprised of multiple chunks.` This is not implemented currently.

**Comment by electricmonk** [comment]
@ronnno what's not implemented? from what I can tell, we us a chunk size of 100.

**Comment by ronnno** [comment]
@electricmonk the spec requires multiple chunk requests until the batch size is reached, and batch size should be larger, possibly a very large number: 
> [Repeat the process until all chunks in the batch have arrived (from one syncing node).](https://github.com/orbs-network/orbs-spec/blob/master/behaviors/services/block-storage.md#synchronization-process)

but we currently have 1 chunk per batch so we must use very small batch sizes (the same size as the chunk size) therefore are unable to sync large numbers quickly.
