### ISSUE TITLE
Update HumanReadable output format

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#176]
1. Shorten the dates (minutes,seconds,microseconds)
2. Merge `service` and `string=adapter` into `component`
3. Change order: sit with @talkol (service, message, node)
4. Shorten node name in the e2e like in acceptance

Find something that allows to grep inside the IDE.

**Comment by talkol** [comment]
More ideas:

1. Use colors, if the text for every node will have a different color, it will be much easier to debug
2. Find an IntelliJ plugin that allows to grep on console logs - like https://plugins.jetbrains.com/plugin/7125-grep-console

**Comment by netoneko** [comment]
Implemented by @IdoZilberberg
