### ISSUE TITLE
Removing (erroneous) transactions from pending pool should call PublicAPI.HandleTransactionError

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#180]
In TXPool, when a transaction has expired in the pending pool before being suggested for a block, spec says we should notify `PublicApi.HandleTransactionError`.

**Comment by electricmonk** [comment]
@OdedWx this is following your change:
https://github.com/orbs-network/orbs-spec/commit/b90872d7518db67ad34c34f0823089acd3c4dfb3

After discussion with @erankirsh, we think this is redundant, as the Public API's waiting requests will probably expire before the cleanup threshold (30 seconds vs 30 minutes).

WDYT?

**Comment by talkol** [comment]
This is not redundant.

A client can send a transaction that will expire in 10 seconds.

Expiry is based on the timestamp encoded in the transaction. We have no control over the value a client encodes there. It often happens in the blockchain world that a client encodes a transaction and takes a long while before actually transmitting it over the wire.

**Comment by electricmonk** [comment]
But regardless, this is an optimization as public API will eventually release the waiting goroutine. What problem are we solving with this?

Shai
________________________________

**Comment by electricmonk** [comment]
Make sure to treat all places touched by the commit:
https://github.com/orbs-network/orbs-spec/commit/b90872d7518db67ad34c34f0823089acd3c4dfb3

(`GetTransactionsForOrdering` is also affected)
