### ISSUE TITLE
Gossip adapter tests become very slow when ran together with count - are we cleaning resources?

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#187]
Running once takes 0.218 seconds

```
$ go test ./services/gossip/adapter -count 1 -timeout 10s -failfast
ok  	github.com/orbs-network/orbs-network-go/services/gossip/adapter	0.218s
```

Running twice takes 0.446s

```
$ go test ./services/gossip/adapter -count 2 -timeout 10s -failfast
ok  	github.com/orbs-network/orbs-network-go/services/gossip/adapter	0.446s
```

Running 10 times takes 6.5 seconds! (x3 slower than expected)

```
$ go test ./services/gossip/adapter -count 10 -timeout 10s -failfast
ok  	github.com/orbs-network/orbs-network-go/services/gossip/adapter	6.526s
```

Not sure why this happens. My guess is that our cleanup after the context is terminated at the end of each tests does not happen immediately (to close all opened connections and goroutines). Which means goroutines and connections are opened faster than they're being closed, resulting in an increasing slowdown.

To improve this, I added an experimental feature that simply goes around and closed all active gossip connections rather aggressively when context terminates. It's in this [unmerged branch](https://github.com/orbs-network/orbs-network-go/tree/feature/experimental-gossip-watchdog) - [this is the commit](https://github.com/orbs-network/orbs-network-go/commit/dba9d334fc42749b52a4ba4318734f53a2a10465). It did not resolve the issue. Need help to continue researching the cause. We also need to decide if this watchdog is a good idea or not.

**Comment by talkol** [comment]
I'm sorry I wasn't clear.. I'm referring to this branch:

https://github.com/orbs-network/orbs-network-go/pull/183

**Comment by talkol** [comment]
Also notice this related issue seen by Shai:

```
go test ./services/gossip/adapter/... -count 100

error 2018-09-17T08:39:53.993035Z gossip transport cannot listen on port 44530: listen tcp :44530: bind: address already in use adapter=gossip function=adapter.(*directTransport).serverMainLoop source=services/gossip/adapter/direct_transport.go:145
panic: gossip transport cannot listen on port 44530: listen tcp :44530: bind: address already in use
```

**Comment by talkol** [comment]
Consider this pattern for graceful shutdown:

https://gist.github.com/rcrowley/5474430

**Comment by electricmonk** [comment]
@talkol is this still an issue?
