### ISSUE TITLE
Strange behavior when running tests with `-timeout` (is this a false positive?)

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#188]
I run this test 100 times with timeout limit of 2 seconds:

```
go test -v -parallel 1 ./services/consensusalgo/benchmarkconsensus/test -run TestLeaderRetriesCommitOnErrorGeneratingBlock -count 100 -failfast -timeout 2s
```

It fails with `panic: test timed out after 2s`

I then run the same again without timeout, and use grep to show how much each passing iteration takes:

```
go test -v -parallel 1 ./services/consensusalgo/benchmarkconsensus/test -run TestLeaderRetriesCommitOnErrorGeneratingBlock -count 100 -failfast | grep "PASS"
```

And it prints:

```
--- PASS: TestLeaderRetriesCommitOnErrorGeneratingBlock (0.06s)
--- PASS: TestLeaderRetriesCommitOnErrorGeneratingBlock (0.07s)
--- PASS: TestLeaderRetriesCommitOnErrorGeneratingBlock (0.06s)
--- PASS: TestLeaderRetriesCommitOnErrorGeneratingBlock (0.06s)
```

I can see all 100 iterations successful and each is taking 0.06-0.07 seconds

My conclusion is that we can't trust the timeout failures. What am I doing wrong?

**Comment by IdoZilberberg** [comment]
Param `-timeout` applies to entire running time of `go test` regardless of what happens inside (e.g. count=n). If you set -timeout=2s it panics after ~2 seconds.
You can see this by running:
`time go test -v ./services/consensusalgo/benchmarkconsensus/test -run TestLeaderRetriesCommitOnErrorGeneratingBlock -count 100 -failfast -timeout 3s | grep PASS`
