### ISSUE TITLE
Fix HTTP server to return data according to spec

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#190]
The current HTTP server implementation is bare minimum to get minimal e2e passing
We need to implement it fully

Spec: https://github.com/orbs-network/orbs-spec/blob/master/encoding/client/binary-over-http.md

**Comment by talkol** [comment]
An important part of this is which errors we should return to the client.

According to the spec, application errors should return HTTP 200 and simply return the client response (eg. `SendTransactionResponse`). This means that `publicapi.SendTransaction` needs to return a valid output in this case and err = nil.

Non-application errors should return HTTP status which isn't 200 and contain the text of the error. This means that `publicapi.SendTransaction` needs to return no output in this case and err != nil

**Comment by noambergIL** [comment]
we have agreed that sendtrasaction if the object is not nil we ignore the err (which is currently anyway just the internal enum in text.

**Comment by noambergIL** [comment]
#223
