### ISSUE TITLE
Acceptance TestNonLeaderPropagatesTransactionsToLeader is flaky

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#194]
It sometimes fails with timeout inside docker (happens a lot on local docker-build.sh)

It continues closing empty blocks, gets to around block 16,000 and then the 1 minute timeout expires

**Comment by electricmonk** [comment]
can you attach an abridged log, with the last successful operation? at which step does it hang?

**Comment by jlevison** [comment]
are we still flaky on this test? is there an action to take here?

**Comment by talkol** [comment]
we'll reopen if it fails again.. closing for now
