### ISSUE TITLE
Many areas in the code are making "RPC" calls (calls between services) when a mutex is locked

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#195]
We should avoid this behavior

Mutexes should be locked for the shortest time possible

Calling a different service while mutex is locked should be avoided - this service might call another method of ours and then we'll have a deadlock

Need to go over all mutexes in the codebase and make sure this doesn't happen

**Comment by electricmonk** [comment]
Where did you see this?

**Comment by electricmonk** [comment]
this issue not operative - this needs to be updated with references to places in code with a problem, or we can take a few hours of concentrated effort to resolve this. Closing for now, @talkol please reopen with some reference if you disagree.
