### ISSUE TITLE
Channels for long running tasks aren't closed

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#198]
When the context is terminated we don't manually close the channels for the long running tasks

Examples:

1. BenchmarkConsensus - `s.successfullyVotedBlocks` is not closed

2. Block Sync - `b.events` is not closed

Why is this problematic? Because after running many tests (with large count for example), these channels remain open and the goroutines that write to them (like the timer in Block Sync) block indefinitely and leak.

If we do a goroutine dump after a while, we see hundreds of these channels and goroutines all stuck

**Comment by electricmonk** [comment]
each service should have a `Stop()` function that closes all resources. This, IMO, is another indication to point us towards a supervised model :),

**Comment by jlevison** [comment]
idiomatic go wise we are not sure that it is required to close channels

**Comment by talkol** [comment]
I think the approach we should take is:

1. No need to close channels (they are GC'ed and closing them is dangerous if not closed by the writer - since writers panic if they write to a closed channel).

2. The main resource we are currently leaking is goroutines. We created a test for this to fail the build if we find leaking goroutines.
