### ISSUE TITLE
Using Digest multiple times for each transaction ... 

### ISSUE THREAD

**Issue by noambergIL** [orbs-network/orbs-network-go#214]
During flow of adding and processing transaction we calc the txHash A LOT of times.
we need it for all kinds of stuff and need it for log tracking #212  (which is just the beginning).

Ideas for imporvement ? 
1) add txHash in the transaction (like receipt) - adds 15%
2) create hash cache 
3) other ?

**Comment by jlevison** [comment]
a normal non-optimized cpu does about 3 million txHash calcs per second.
we can try to benchmark on a server, but even at 3mil/sec i am not sure we need to invest into optimizing this for now.

**Comment by electricmonk** [comment]
kinda duplicates #321
