### ISSUE TITLE
Improve E2E on docker now that we have multiple E2E tests

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#224]
We now have multiple E2E tests, we should fix docker to reflect this in `docker-test.sh`

1. Run every E2E test on a its own clean environment (so tests don't affect each other)

2. Save the logs for every E2E test separately so we can differentiate between their logs

**Comment by electricmonk** [comment]
No no no!
E2E tests should never run in clean environments, as we expect the production system to be able to handle multiple concurrent flows
We definitely need to save the logs for each test separately, which is another use case for distributed tracing, as discussed with @netoneko and @noambergIL

**Comment by talkol** [comment]
ok, so let's do only 2 for now

The main problem is that it's very hard to debug a failing test because the tests before it contaminate the entire state

Also, tests like checking block sync (new node flow) I think we will have to add to E2E. This is because the common flow in the system is to start a new node when the network is already working, so 99% of the time new nodes will start by block syncing..
