### ISSUE TITLE
Suggestion: log goroutine ID on every log message

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#225]
If every log line included the goroutine ID we could have an easier time understanding deadlocks or if one of the goroutines stopped working

Problem is there's no staightforward way to get goroutine IDs:

https://blog.sgmansfield.com/2015/12/goroutine-ids/

But this one may be ok - "The Legitimate CGo Version".. (from the post)

**Comment by electricmonk** [comment]
there's an even better cool thing we can do with `Context`s - add debugging parameters that propagate through the contexts and get logged. The context can hold a specialized debugging context, a kind of key-value store where all pairs get added to the log automatically
https://golang.org/pkg/context/#example_WithValue

**Comment by electricmonk** [comment]
duplicates #299
