### ISSUE TITLE
CalcRipmd160Sha256() calculates the wrong value

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#231]
inside crypto/hash/hash_test.go:

```
var someData = []byte("testing")

const (
	ExpectedSha256         = "cf80cd8aed482d5d1527d7dc72fceff84e6326592848447d2dc0b0e87dfc9a90"
	ExpectedSha256Ripmd160 = "cf80cd8aed482d5d1527d7dc72fceff84e6326592848447d2dc0b0e87dfc9a909c1185a5c5e9fc54612808977ee8f548b2258d31"
)
```

`CalcRipmd160Sha256()` IMO should return Ripemd160(Sha256(data)) meaning hash of hash

The test IMO verifies we return the concatenation of the two hashes, which isn't what we want..

**Comment by talkol** [comment]
Please verify with @OdedWx that indeed its hash of hash and not concatenation

**Comment by OdedWx** [comment]
Exactly, It's Ripemd160(Sha256(data))
The output should be 20-Bytes

**Comment by talkol** [comment]
Fixed in https://github.com/orbs-network/orbs-network-go/commit/029f3363db27982d0f00ee9e76e1012ebdacfb48

@jlevison please review I used the API correctly
