### ISSUE TITLE
Need to verify Signer network type (test net or main net) when verifying the signer in virtual machine

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#235]
Missing.. also make sure this appears in the spec

**Comment by talkol** [comment]
I'll add to vm, @OdedWx you add to spec?

**Comment by electricmonk** [comment]
@OdedWx are we ok with killing network type altogether?

**Comment by electricmonk** [comment]
as far as I'm concerned, Network Type is deprecated. If anyone disagrees, please reopen.
