### ISSUE TITLE
TXPool service <> pendingPool cyclic dependency

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#236]
TXPool uses its `pendingPool` extensively
`pendingPool` needs to notify the service on transaction removal so that it can call PublicAPI with the results

There is a cyclic dependency I'm unhappy with but don't yet have enough evidence to solve

**Comment by talkol** [comment]
@erankirsh can you sit with Shai for 10 minutes and see if you have a more elegant solution? seems this is the sort of problems you give great advice for

**Comment by electricmonk** [comment]
Closing for now, this is smelly but good enough at this point.
