### ISSUE TITLE
SDK environment can't start gamma-server

### ISSUE THREAD

**Issue by kfirdm** [orbs-network/orbs-network-go#238]
When running "gamma-cli start "
Output is: 
gamma-server started and listening on port 8080
Could not start gamma-server fork/exec **./**/usr/local/bin/gamma-server: no such file or directory

I guess this line is causing it: 
https://github.com/orbs-network/orbs-network-go/blob/108ca29a44ea98a28e6d3a651eec57d0ae18ebed/devtools/jsonapi/commands/start.go#L47

**Comment by electricmonk** [comment]
@itamararjuan please update status

**Comment by netoneko** [comment]
It was fixed by me a month ago.
