### ISSUE TITLE
Direct transport long reconnect timeout causes E2E test to always start after timeout

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#272]
If reconnect timeout is 5 seconds, the first node will always fail to connect to peers (since others did not start yet) and will only reconnect after 5 seconds and only then consensus can start

**Comment by talkol** [comment]
Reported by @netoneko 

Temporary solution was to reduce the reconnect timeout

**Comment by talkol** [comment]
Good ideas. We already planned to implement the backoff but your second suggestion is also interesting

**Comment by netoneko** [comment]
Is it still relevant?
