### ISSUE TITLE
Direct transport is blocking on send and receive - what happens on network partitions?

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#273]
1. What happens if one of the peers disconnects? Will the `socket.Send` block there or be immediate? This is a network split.

2. What happens if the outgoing socket buffer is full? Will the `socket.Send` block there or be immediate? This is a bandwidth issue (max capacity).

**Comment by talkol** [comment]
Had a short discussion on this today with @OdedWx @electricmonk @erankirsh 

The things that came up:

1. There is agreement that sends and receives should in general be *blocking*. The reasoning is that we already have a queue (the OS socket buffer) and we prefer to rely on it instead of adding a new queue on top. This will also throttle the speed of the system according to the available bandwidth.

2. Queue theory says that we should never block send and receive with each other. This means that a single goroutine cannot handle both `gossip.Send` and `gossip.Receive` for any use case. For example, in `benchmarkconsensus` we have the main consensus loop goroutine. It currently does the `gossip.Send` and the gossip goroutines do the `gossip.Receive` (running the listener handlers). If we change to the channel pattern (instead of the mutex pattern) and we'll cause the gossip goroutines to send the message via a channel to the consensus main loop goroutine for handling, then the consensus goroutine will handle the `gossip.Receive` as well.. which goes against the blocking send and receive together (queue theory no no).

3. Broadcasts are an issue that requires further thought and discussion. We don't have a good solution there yet. In a system that relies on consensus, we don't need to wait until all peers receive the broadcast. Even worst, if some of the peers are byzantine, we don't want to wait for them. We obviously want to broadcast to all of the peers concurrently, but we don't want to block until the sockets queue the request in *all* of them. What should we do?

4. QoS between topics is also an interesting and complex issue. The system might eat up its bandwidth on transaction forwards and not have enough bandwidth to reach consensus. Does it mean that consensus should have higher priority than tx forward? Not necessarily. The relationship between them is complex and we can't favor one over the other. There's probably some sweet spot between them. Currently, we don't think we need to implement QoS between topics. Since the system is based on consensus, even if the link to some peers is saturated, consensus could move forward.

@noamoded @kirill your feedback is also requested here

**Comment by electricmonk** [comment]
Note that this means that messages cannot be treated as "delivered" anymore as they might be in the queue when the system shuts down. I'm pretty sure that's already the case, but are we *sure* we have no assumptions on delivery?

**Comment by talkol** [comment]
We currently don't make any assumptions on delivery. Any message that requires such assumptions has an application layer ack (a separate response message).

Also, in the current blocking implementation we can't treat messages as delivered either. Send returns successfully only when the message is placed in the OS outgoing queue for the socket. It doesn't mean that the peer acknoloedged reception on the TCP level... these messages theoretically can still fail on TCP
