### ISSUE TITLE
Improve the way config travels from docker to main to Node

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#28]
Can we make the docker images identical for all nodes? This means they can't have any configuration on them.

Assume we have 50 configuration params - that can also vary by blockHeight! Is there any better way to pass them to docker except 50 environment variables?

**Comment by talkol** [comment]
Consult with @electricmonk on this please

**Comment by electricmonk** [comment]
@talkol I think this is no longer a problem. Closing, please reopen if you disagree
