### ISSUE TITLE
Update log.Meter API

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#297]
Follow up from #269

We should support following behavior:

1. `Done()` (maybe `Success()`?) for happy flow
2. `Timeout()` for timeouts
3. `Fail()` (and maybe `FailWithError(err)`) for errors

**Comment by jlevison** [comment]
i think a metric should be a metric, meaning it should represent a number and a context to that number, but no more info - the fact that we are now outputting them to the log is not optimal, and we should not extend them into a second logging system - its does not directly conflict this issue, but just something to keep in mind
