### ISSUE TITLE
suggestion : fail the tests if the log contains errors (e2e)

### ISSUE THREAD

**Issue by noambergIL** [orbs-network/orbs-network-go#308]
e2e should not contain error logs 
in component/unit tests maybe we need a matcher like "VerifyNoErrorLogs()" 
and/or a logger that fails the tests if it is called with a log.Error()

we have lots of long tests that may succeed even with log of errors we should know about this
(example of the graceful shutdown doesn't succeed usually the test will succeed but it can be a problem)

**Comment by talkol** [comment]
Not sure we need the regexp yet

I think `VerifyNoErrorsInLog` is enough because 90% of the tests (almost everything except stress) should have zero errors. If they don't and this isn't a bug, these errors should probably be `Info` and not errors.

**Comment by electricmonk** [comment]
Not exact; any test that uses the `TamperingTransport` might yield errors; should these errors appear as errors in the log? if not, why are we even logging them?

My thoughts are that in a test that creates errors, we *know* which types of errors we expect, hence my suggestion for an "unexpected errors" assertion

**Comment by talkol** [comment]
If a test creates errors then don't use this matcher in the test..

**Comment by electricmonk** [comment]
related to #171
