### ISSUE TITLE
8080 port collisions in http server happens in tests.

### ISSUE THREAD

**Issue by noambergIL** [orbs-network/orbs-network-go#309]
e2e & gamma both try and use the same port and run in parallel (diff packages)

**Comment by noambergIL** [comment]
was asked to assign to itamar and ask that the e2e will have random ports ...

**Comment by talkol** [comment]
I'm not sure the random ports is worth the added complexity. This feature is only relevant for tests.

To add the randomized ports (port 0), we need to add a way to query the node for the port. This is will add some noise. First, we probably need to change the `Node` interface for this silly query.

```
type Node interface {
	GracefulShutdown(timeout time.Duration)
	WaitUntilShutdown()
}
```

And also add this silly query to the HTTP server interface:

```
type HttpServer interface {
	GracefulShutdown(timeout time.Duration)
}
```

Not sure this is worth the trouble.

We changed the fixed ports to be different between `gamma` and `e2e` and the flakiness seems to go away.

**Comment by talkol** [comment]
https://github.com/orbs-network/orbs-network-go/pull/311
