### ISSUE TITLE
Improve directory structure of general file folders (non-code)

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#313]
In the root of the project we have:

* `/logs` which contain the runtime node logs when saved to file

* `/e2e-config` which contains JSON configs for e2e

Can we organize these folders a bit better?

* Maybe rename `logs` to `_logs` so it's clear it's not part of the build (right now it looks like it's a Go package named `logs`)

* Maybe move `/e2e-config` to be under the `/test/e2e` folder? Something like `/test/e2e/_config` again with the underline convention to say that it isn't part of the build

In general, the `go build` and `go test` tools ignore folders that start with underscore, so it's a clear way to mark folders that aren't part of the build

**Comment by netoneko** [comment]
Fixed in #427
