### ISSUE TITLE
Handle long-running goroutines

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#318]
Currently if a long-running goroutine panics and crashes, no one will know about it, leaving the node half-dead.

We need to, at the very least, add monitoring when each goroutine dies unexpectedly (via shared infrastructure), or preferably implement some sort of supervision scheme.

This is a blocker for mainnet IMO.

@erankirsh @talkol thoughts?

**Comment by talkol** [comment]
Currently if a long running goroutine panics, it will print to the error log
