### ISSUE TITLE
CI metrics should be based on separate benchmarking build step

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#326]
Currently we base our CI metric dashboard on a build flow that stresses the system in acceptance mode (in-memory); this doesn't really reflect the system's behavior for two reasons:

1. the system is being tampered with during these tests
1. it doesn't run the e2e flow, so no TCP network, no filesystem (when we add real persistence), etc

We should add another (parallel) build step that runs a real stress test (such as the `BenchmarkE2ENetwork` under `test/e2e`) for a few minutes, and only collect logs emitted during that step to base dashboards on.

**Comment by netoneko** [comment]
We are not benchmarking anything at this point.
