### ISSUE TITLE
Gamma missing features

### ISSUE THREAD

**Issue by erankirsh** [orbs-network/orbs-network-go#330]
- Calling contract methods and sending transactions using different singers. 
- Clear error messages - using string and not code
- Support getTranscationStatus
- Contract calling other contract 
- Mute xCode warrining. 
- Block explorer api - get Transactions by block height. 
- Remove the need to enter computer password and direct the terminal to the workspace folder. 
- Working with Address - minor improvements - mainly passing "0x".
- Generate multiple keys and address into file.  
- Deploy contract response formatting.

**Comment by electricmonk** [comment]
@erankirsh is this in the scope of Gamma CLI or Gamma?

**Comment by electricmonk** [comment]
@andr444 I'm closing this, please take over the product for gamma-cli and if there's anything here you still feel is relevant, open discrete issues.
