### ISSUE TITLE
Refactor GetBlocks method in block storage

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#333]
It's used heavily in block sync but implementation is very naive.

**Comment by yonidavidson** [comment]
I don't know how many blocks are but every iteration you do append to the blocks you reallocate the memory.
the trick is to create the blocks slice with 0 length and length(allblacks). this way, you won't have to allocate the memory every iteration. (taken from https://www.calhoun.io/how-to-use-slice-capacity-and-length-in-go/)
`	blocks = make([]*protocol.BlockPairContainer, 0, len(allBlocks))
`

**Comment by netoneko** [comment]
Fixed by @danokoch and @talkol in #474
