### ISSUE TITLE
Block Storage issues

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#336]
https://github.com/orbs-network/orbs-spec/blob/master/behaviors/services/block-storage.md

1. The 3 calls to `HandleBlockConsensus` don't all have the right argument (`HANDLE_BLOCK_CONSENSUS_MODE_UPDATE_ONLY` vs `HANDLE_BLOCK_CONSENSUS_MODE_VERIFY_AND_UPDATE `)

2. Block Sync on init does not start immediately, but only after successful commit timeout passes

3. Block Sync "pre-synchronization" phase is not implemented (where `HandleBlockConsensus` is called with latest persistent block)

4. When block storage tries to commit an old block, when TxHeader is available, we need to compare the header itself (byte compare) if the timestamp matches, it's not enough to rely on timestamps

**Comment by talkol** [comment]
@netoneko and I fixed some of these together in an emerging PR

**Comment by jlevison** [comment]
all of the issues above are handled in the bugfix/block-sync-acceptance-test branch
