### ISSUE TITLE
Log was not uploaded in circleci when a gamma test failed

### ISSUE THREAD

**Issue by itamararjuan** [orbs-network/orbs-network-go#372]
https://circleci.com/gh/orbs-network/orbs-network-go/2453

The link contains an example when no artifacts were uploaded from the build

**Comment by electricmonk** [comment]
@itamararjuan did you fix that?

**Comment by itamararjuan** [comment]
Hi @electricmonk  yep it was fixed a couple of days ago and merged to master.
