### ISSUE TITLE
Fix flakiness on BlockStorage tests

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#379]
This has to do with Block Storage test harness.

Error message is:

panic: Mock call missing for:
BroadcastBlockAvailabilityRequest

**Comment by talkol** [comment]
Duplicate of https://github.com/orbs-network/orbs-network-go/issues/362

**Comment by electricmonk** [comment]
should be fixed in #385 , right, @jlevison?
