### ISSUE TITLE
Rename "acceptance" CI phase to "flakiness" and add some component tests there

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#384]
1. We want to run more tests under the flakiness count 100 test - for example component tests of block storage. These component tests are flaky too and currently we're missing a structured way to discover the flakiness in them.

2. This means it's not really an "acceptance" phase, it's a "flakiness" phase.

    Rename the following:

    name of the CI phase from `acceptance` to `flakiness`
    `test.acceptance.sh` to `test.flakiness.sh`
    `Dockerfile.acceptance` to `Dockerfile.flakiness`
    `docker-test.acceptance.sh` to `docker-test.flakiness.sh`
    `docker-compose.acceptance.yml` to `docker-compose.flakiness.yml`
    and so forth...

**Comment by electricmonk** [comment]
While I agree with the rename - why do we want to run the component tests of block storage 100 times? they should be deterministic
