### ISSUE TITLE
another flakiness in block sync?

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#387]
```
--- FAIL: TestBlockSyncStaysInIdleOnBlockCommitExternalMessage (0.02s)
	require.go:687:
			Error Trace:	block_sync_test.go:38
			Error:      	Object expected to be of type *sync.idleState, but was *sync.collectingAvailabilityResponsesState
			Test:       	TestBlockSyncStaysInIdleOnBlockCommitExternalMessage
			Messages:   	state should remain idle
```

**Comment by jlevison** [comment]
could be, it means that a sleep of 500 microseconds took more than 8ms. this is also related to another test which i set to skip until i rebuild the sync event conduit, i will fix it then

it could be though that for this test i might have to extend the times as it needs to checks that while blocks are incoming the state stays on idle
