### ISSUE TITLE
Go over mutex use in block storage

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#398]
*This is a warm up task for @danokoch (I can't assign yet since he didn't accept the org invite)*

**Some background:**

1. The go API for mutex is available here: https://golang.org/pkg/sync/
2. I wrote down our best practices for using a mutex here: https://github.com/orbs-network/orbs-network-go/blob/master/CONTRIBUTING.md#mutex-best-practices
3. Here is an example PR where I fixed some mutex issues according to these best practices: https://github.com/orbs-network/orbs-network-go/pull/353

**The task:**

Go over the service block storage and do a code review for the mutex use on the service itself:
https://github.com/orbs-network/orbs-network-go/blob/master/services/blockstorage/service.go#L28

I noticed some issues there that should be improved according to the best practices.

It's your call whether you want to do a PR or just open an issue and recommend how to fix. I think PR is better :wink:

**Comment by talkol** [comment]
@jlevison will help review once finished

**Comment by danokoch** [comment]
Fixed by #474
