### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#44]
This seams like the most popular and comprehensive choice:

https://github.com/alecthomas/gometalinter

**Comment by electricmonk** [comment]
@netoneko please integrate a linter ASAP, start with a simple rule to reject commits with `t.Skip()`

**Comment by electricmonk** [comment]
We have integrated Golangci.com; this task revolves around deciding if it's good enough, or whether we want to define extra / our own linting rules
