### ISSUE TITLE
BlockStorage.GetTransactionReceipt maybe should not fail if receipt not found

### ISSUE THREAD

**Issue by danokoch** [orbs-network/orbs-network-go#448]
https://github.com/orbs-network/orbs-spec/blob/master/behaviors/services/block-storage.md#gettransactionreceipt-method

spec is not clear what to do in this case, seems that we shouldn't fail although the current implementation does

**Comment by jlevison** [comment]
the current implementation for this function needs to be rebuilt, there was a problem with the spec (wrong assumptions regarding bloom filters)
as we are moving to taiga to manage work we should reference this there @EsterEdelstein @erankirsh

**Comment by ronnno** [comment]
resolved in V1
