### ISSUE TITLE
Proposed refactor in block sync component tests

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#452]
Many of the tests have `.When` directly in the test body

This is very hard to work with, makes the tests less readable and impossible to refactor

According to the conventions in the rest of the code, in our refactor we moved the `.When` into the harness, so we're left with an expressive function call that's easier to understand.. and if you want to refactor the `.When` calls, it's much easier because we now have one instance of each

Here's an example:

https://github.com/orbs-network/orbs-network-go/blob/bugfix/block-storage-mutex/services/blockstorage/sync/state_waiting_for_chunks_test.go#L31

```
// we moved this When to the harness
h.expectLastCommittedBlockHeight(primitives.BlockHeight(0))

// this When is still outside and we recommend it should be moved as well
h.gossip.When("SendBlockSyncRequest", mock.Any, mock.Any).Return(nil, nil).Times(1)
```

**Comment by jlevison** [comment]
@danokoch , tal discussed this with me and i completely agree, lets make that change and move it into the harness, a classic refactor after the work is done to make the code better

**Comment by noambergIL** [comment]
please run linter and when done please remove the line with services/blockstorage from the .golangci.yml
