### ISSUE TITLE
Some improvements for logger

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#46]
1. Move to package `log` or `reporting` under `instrumentation`

2. Change the order of the stack trace (param `function`) and my parameters since now I can't see the params in human readable (and the stack trace param is not very interesting)

3. Add interface Error support with unwrapping, cause and stack trace (don't just cast to string)

4. Add a few tests with membuffers to see that the print to string looks good (`TransferTransaction.Build().String()`)

5. Think about tab formatting in human readable so its easier to split fields with your eyes

**Comment by jlevison** [comment]
#48 handles 2. in the list

**Comment by IdoZilberberg** [comment]
When I pass two parameters:

```
testLogger.Info("Creating acceptance test network", instrumentation.String("consensus", consensusAlgo.String()), instrumentation.Uint32("num-nodes", numNodes))
```

I would like the order to be kept in the log, because right now it changes their order and prints:

```
info 2018-07-31T13:47:59.753888205Z Creating acceptance test network num-nodes=2 consensus=CONSENSUS_ALGO_TYPE_LEAN_HELIX function=harness.NewTestNetwork source=/Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/test/harness/network.go:55 
```

**Comment by IdoZilberberg** [comment]
Also, the fields given with `For` on construction should be printed last right before the `function`:

```
info 2018-07-31T13:59:59.708543719Z Entered consensus round, last committed block height is node=dfc06c service=consensus blockHeight=0 function=leanhelix.(*service).consensusRoundRunLoop source=/Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/consensusalgo/leanhelix/service.go:94 
```

**Comment by talkol** [comment]
Actually regarding the last comment, the fields given with `For` on construction should be printed first before any other fields, in the order of the `For`. Meaning the `node` should be first, then `service`

**Comment by talkol** [comment]
Can you please make the timestamp always the same length:

```
info 2018-08-02T12:10:40.321678385Z consensusContext error consensus-algo=benchmark function=benchmarkconsensus.(*service).leaderConsensusRoundRunLoop source=/Users/talkol/go/src/github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus/leader.go:23 
info 2018-08-02T12:10:40.326842924Z Consensus round waking up after retry timeout consensus-algo=benchmark function=benchmarkconsensus.(*service).leaderConsensusRoundRunLoop source=/Users/talkol/go/src/github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus/leader.go:33 
info 2018-08-02T12:10:40.32701077Z Generating new proposed block for height blockHeight=1 consensus-algo=benchmark function=benchmarkconsensus.(*service).leaderGenerateNewProposedBlockUnderMutex source=/Users/talkol/go/src/github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus/leader.go:93 
info 2018-08-02T12:10:40.327038597Z consensusContext error consensus-algo=benchmark function=benchmarkconsensus.(*service).leaderConsensusRoundRunLoop source=/Users/talkol/go/src/github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus/leader.go:23 
```

**Comment by talkol** [comment]
In `function` field, can we make the path shorter and start from source root:

```
source=/Users/talkol/go/src/github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus/leader.go:23 
```

will be nicer as:

```
source=services/consensusalgo/benchmarkconsensus/leader.go:23 
```

**Comment by talkol** [comment]
bump. we rely on the logger a lot for debugging and these improvements will decrease the time it takes us debugging by making the log more usable. please prioritize this

**Comment by talkol** [comment]
Another request - add `instrumentation.StringableSlice` which takes a generic slice of `interface{}` and prints it by running `String()` on each element

**Comment by jlevison** [comment]
#91 will handle all the issues with the exception of the error hooking and the package rename, which will be handled this week in another PR
