### ISSUE TITLE
Test startup time of first consensus round

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#477]
I noticed that in testnet the first consensus round doesn't start until all the nodes are online, although the quorum size is 66%. I would be happy to be proven wrong, but we have no tests for it.

As @talkol suggested, the course of action should be the following:

1. [x] change quorum size from 100% to 66% in acceptance and verify that it runs smoothly
1. [ ] add an acceptance test that starts 2/3 of the nodes and verifies that the blocks are being created

**Comment by netoneko** [comment]
1. Addressed in #485

**Comment by electricmonk** [comment]
Working on 2
