### ISSUE TITLE
Unify the API acceptance tests and e2e use to interact with BenchmarkToken

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#495]

**Comment by netoneko** [comment]
I suggest we make use of client SDK here. @talkol, what do you think?

**Comment by electricmonk** [comment]
e2e should definitely use client sdk
acceptance can't, but what I *really* want is an abstraction like we have today, representing `BenchmarkToken` and other test contracts, that is using the same semantics (exposing the same API) to both e2e and acceptance, with the e2e impl using the client sdk, and the acceptance impl accessing PublicAPI directly
