### ISSUE TITLE
Convert configs to standard config mechanism

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#50]
Please convert the configs to the standard way config are defined in the system

Notice this:
https://github.com/orbs-network/orbs-network-go/blob/3cb919e064be64ebecf7c5c1e372c65f52abce60/services/blockstorage/service_config.go#L13

It does not appear here:
https://github.com/orbs-network/orbs-network-go/blob/3cb919e064be64ebecf7c5c1e372c65f52abce60/config/hardcoded_config.go#L11

Also notice this config:
https://github.com/orbs-network/orbs-network-go/blob/3cb919e064be64ebecf7c5c1e372c65f52abce60/main.go#L33

It's also not standard

Please have a session with @electricmonk about how he designed the configuration in the node and what's the correct way to plug into it

**Comment by jlevison** [comment]
already fixed in 5aa229e36f7394475fd86ca11d97e393aa039776
the branch will be merged today
