### ISSUE TITLE
Fix e2e tests so they can run multiple times without risk on the same network

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#500]
E2E used to assume that the tests run once on a new network, but that changed when we started running e2e on the test net (same network instance)

We now improved them but we need to improve further because they will eventually fail

1. Transfer test
    We are sending tokens from the same account that has 1,000,000 but it will eventually run out of tokens. We should add minting capability to benchmark token and then mint new tokens during the test.

2. Deploy test
   We are deploying a counter with a random name but these names will eventually collide. We should switch to a name based on a GUID.

**Comment by netoneko** [comment]
Fixed.
