### ISSUE TITLE
This code does not compile on master

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#51]
https://github.com/orbs-network/orbs-network-go/blob/3cb919e064be64ebecf7c5c1e372c65f52abce60/services/blockstorage/test/commit_block.go#L13

**Comment by talkol** [comment]
Here's how it looks on my end, just to be clear on what's the problem:

https://i.imgur.com/vQDJ4U5.jpg

**Comment by jlevison** [comment]
its a goland issue, it does compile, nevertheless it was fixed for us humans in a branch that will be merged today
