### ISSUE TITLE
Please remove all panics from the service

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#52]
https://github.com/orbs-network/orbs-network-go/blob/3cb919e064be64ebecf7c5c1e372c65f52abce60/services/blockstorage/service.go#L263

Service is not allowed to panic on conditions that are external to the system

If the spec says "panic" it's just a saying.. the spec was written before we chose Go language for this implementation, the panic there is not a golang panic

**Comment by jlevison** [comment]
this was actually documented - we do need to define for each case what is the desired behavior - see https://github.com/orbs-network/orbs-spec/issues/50 for example

**Comment by netoneko** [comment]
Fixed in b282c121e386d652c6d0308e50aaf338c7bf7f0d
