### ISSUE TITLE
Please find a more elegant way to do this than a polling goroutine

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#54]
https://github.com/orbs-network/orbs-network-go/blob/3cb919e064be64ebecf7c5c1e372c65f52abce60/services/blockstorage/service.go#L88

I doesn't seem elegant to me to create a new goroutine on every method call. Also polling is also pretty bad for a language that has dozens of synchronization mechanisms.

Please find a way to resolve this without polling. If you need to learn more about go synchronization mechanisms, please do.

Also, don't use sleeps in production code:
https://github.com/orbs-network/orbs-network-go/blob/3cb919e064be64ebecf7c5c1e372c65f52abce60/services/blockstorage/service.go#L102

Find other ways to implement this, like using `time.After` and a `select`. Please read the implementation for `consensusalgo/benchmarkconsensus` thoroughly if you want to see examples of go synchronization patterns.

**Comment by talkol** [comment]
I now saw that you improved it significantly in a branch 👍 

https://github.com/orbs-network/orbs-network-go/blob/219806ef552e5f039506dfffa66e04f15ddbeb02/services/blockstorage/service.go#L97

nice work!

I still believe that we can think of a way to do this without polling every 10 ms though..

Some ideas to do that:

1. Use `sync.Cond` and `Broadcast` every time we commit a new block successfully - this can reduce the polling to poll on new block instead of every 10 ms. I'm not sure this will play nice with `select` though.

2. Create a map of channels, one channel for every block height we're waiting for (let's say we're called when block height is 5, then I'm waiting until block height 10 arrives). All goroutines that wait for this block height will block read from this channel. Once the height arrives, we close the appropriate channel in the map if one exists. Once we close it, all goroutines that wait on it will be released. This will play with `select` but it creates lots of channels..

**Comment by jlevison** [comment]
good ideas, i agree that busy waiting (even if we probe) is not a good practice, leaving this issue open so we address it later as we have a better sense of the entire implementation
