### ISSUE TITLE
Please follow the spec and make this configurable

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#55]
https://github.com/orbs-network/orbs-network-go/blob/3cb919e064be64ebecf7c5c1e372c65f52abce60/services/blockstorage/service.go#L85

The number 5 is not hardcoded anywhere, it's just an example

**Comment by jlevison** [comment]
indeed, and its one of the comments on the code, it should not be configuration, it should come from the behavior of the contract/vchain (or something else, need to implement more)

**Comment by talkol** [comment]
You can add it to the configuration in `/config`

All the configuration there will eventually come from contract/vchain configs

Currently we're using the in-memory hard-coded config just to for tests, the real deal will have an implementation that conforms to the same interface and will take the data from elsewhere
