### ISSUE TITLE
Monotonous timestamp validation in consensus context, no more nil prev block in HandleBlockConsensus

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#560]
There's a new "tiny" feature that was recently added to the spec that involves a pretty wide integration. Since it affects several stakeholders, we should coordinate this effort.

Consensus context needs to validate that the timestamps used for new blocks are monotonous. Since it's stateless, it needs a way to get the previous block timestamp.

Stakeholders:

1. @OdedWx - finish and formalize the spec for this, in the original discussion about this we wanted to avoid having consensus context querying another service for this data. Instead, we want consensus context to receive the previous block timestamp in the RequestTransactionsBlock RPC method as argument (just like it receives the previous block hash).

2. @IdoZilberberg - implement the consensus context change. Also, this means that all callers to consensus context - the consensus algos need to supply this info. Ido will take care of LeanHelix. There are two places where the algo calls consensus context to create/validate a transactions block - (1) as part of the consensus loop (2) during HandleBlockConsensus flow coming from block sync. Flow (1) should already have the prev block available (in the last committed block state variable), we only need to fix the interface between the algo and the library with @Gad's help. Flow (2) should receive the prev block pointer as argument. The problem is that it's currently passed as nil.

3. @talkol - needs to do the same algo change in benchmark consensus. It's the exact same flows (1) and (2) like above.

4. @ronnno or @jlevison - Make sure that block storage never calls HandleBlockConsensus with prev block as nil as part of block sync. Currently it does. The problem is that block sync doesn't have the prev block and we need to figure out what's the best place to give it. We might need to change adapter to support this. So whenever the block adapter provides GetLastBlock (and returns the last block and the timestamp for it), it will always return also the prev block to it. The adapter will then need to cache the two latest blocks instead of the last only.

https://tree.taiga.io/project/orbs-network/epic/502

**Comment by electricmonk** [comment]
@IdoZilberberg please evaluate this issue and either close or assign for work in Q32019

**Comment by OdedWx** [comment]
Handled in v1 spec, by having the ConsensusAlgo maintaining the previous block header state and passing the relevant state (timestamp and block hash) with ValidateBlock.
