### ISSUE TITLE
Support log.Diff to represent expectation mismatch

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#57]
Expected API:

`logger.Error("protocol version mismatch", log.Diff(protocol, expectedProtocol)`

**Comment by talkol** [comment]
I think it's pretty much immediate with https://github.com/google/go-cmp which we already use

https://godoc.org/github.com/google/go-cmp/cmp#Diff

and it will hopefully work with membuffers since membuffers works with `Equal()` all around
