### ISSUE TITLE
Add sync mechanism for shared variables in StateStorage

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#68]
Some recommendations:

1. The following line should be protected under a mutex:

https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/statestorage/service.go#L34

You have no guarantees on which goroutine the function `CommitStateDiff` will be called, so it might be called concurrently

This is btw the simple [pattern](https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/consensusalgo/benchmarkconsensus/non_leader.go#L14) we use to protect.

2. Recommend to rename `lastResultsBlockHeader` to `lastCommittedBlock`

It's a common pattern we have in almost all services. One [example](https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/consensusalgo/benchmarkconsensus/service.go#L38). Block storage also should have the same variable and Transaction pool, this variable I think also appears in the spec in all of them under this name. It's used for all the inter-node synchronization.

3. Recommend to extract logic from `service.go` and leave only routing boilerplate in it

See for example this [service.go](https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/consensusalgo/benchmarkconsensus/service.go) and this [extracted logic](https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/consensusalgo/benchmarkconsensus/non_leader.go) from it.

When you have lots of stuff the code is doing, you can separate to different logic files per domain. The one huge service.go file is hard to read..

**Comment by noambergIL** [comment]
in #72 we have done 1 , 2

about 3 since state storage is one we don't want to seperate to two file where the internal func would be called xImpl as it has no distiction from the func itself
