### ISSUE TITLE
limit gossip message size

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#682]
Currently an incoming gossip message is bound by 1TiB in memory:

`MAX_PAYLOADS_IN_MESSAGE * MAX_PAYLOAD_SIZE_BYTES = 1TiB`

A malicious transmission can easily crash the gossip service process

- consider moving these limits to configuration
- consider limiting the overall gossip transmission size to something that can fit in memory

**Comment by netoneko** [comment]
Fixed in a70bd1b2e7a1c8880060ecd0e3fa442b883818c9
