### ISSUE TITLE
Optimization postponed in ValidateBlockForCommit

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#684]
- Spec describes optimization to perform structural verification on blocks in BlockStorage
- Optimization is out of scope for V1
- Spec should be updated to reflect that (https://tree.taiga.io/project/orbs-network/us/438?kanban-status=1639113)
- When implementing optimization `HandleBlockConsensusInput` should change to exclude results and transactions blocks and include only block proof. And, structural verification should be done on BlockStorage side before notifying ConsensusAlgo

**Comment by electricmonk** [comment]
@OdedWx @gadcl is this still relevant?
