### ISSUE TITLE
Some recommendations for refactors in Block Storage

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#69]
1. Recommend to merge `lastCommittedBlockHeight` and `lastCommittedBlockTimestamp` to a single variable `lastCommittedBlock`

It's a common pattern we have in almost all services. One [example](https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/consensusalgo/benchmarkconsensus/service.go#L38). State storage also should have the same variable and Transaction pool, this variable I think also appears in the spec in all of them under this name. It's used for all the inter-node synchronization.

2. Recommend to extract logic from `service.go` and leave only routing boilerplate in it

See for example this [service.go](https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/consensusalgo/benchmarkconsensus/service.go) and this [extracted logic](https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/consensusalgo/benchmarkconsensus/non_leader.go) from it.

When you have lots of stuff the code is doing, you can separate to different logic files per domain. The one huge service.go file is hard to read.. One domain for example is the commit flow which can be put in commit.go and another domain is the sync flow which can be put in sync.go

**Comment by jlevison** [comment]
i am promoting this to a US in taiga, will merge the block stuff as suggested, good idea, i am not sure about extracting the logic as i am not sure we will have any other logic 'driver' for the block storage, but let me think about it some more. it will be done as part of the transaction receipt branch i am working on now

**Comment by jlevison** [comment]
https://tree.taiga.io/project/orbs-network/us/100
