### ISSUE TITLE
Do we include compilation errors and panic stack traces in transaction output

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#696]
The PRO is that this makes the system much easier to work with (if a contract doesn't compile or crashes on main net or test net you can debug it)

The small CON is that it stores junk on the blockchain forever

The bigger CON is that these verbose errors are not necessarily identical between all nodes and therefore will not pass consensus and fail the entire block (this is a problem - an attacker could create a liveness problem). We could resolve it somehow by taking the output in this case from the leader only..

**Comment by electricmonk** [comment]
@OdedWx we discussed this recently again - do you want to move forward with logging SDK?
