### ISSUE TITLE
Block height notion must be added to StateStorage adapter

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#70]
The current adapter interface for **write** needs to be changed a bit

This is the current interface:

https://github.com/orbs-network/orbs-network-go/blob/6462358e93af3532e0b26c1da12ce5011815c2f0/services/statestorage/adapter/persistence.go#L9

1. We need to add here a notion of `block height`. State storage needs to keep state changes for about 5 blocks back.. if we don't know what block height we're updating how can we keep this log? I recommend to add the block height as one of the parameters.

2. The state writes in the system are always done per complete blocks. We can't update in the system the state for half a block or one transaction from a block. The current interface that writes in a resolution of a single contract is dangerous because it isn't transactional. If the first succeeds and the second fails we won't undo the first. I recommend to change the interface to receive all the state diffs from a block together. Then the persistence layer either handles all of them successfully or none of them (make it fully transactional).

The next thing we need to do is the following:

1. Add a latch mechanism in the in memory adapter that allows to wait until the state for a specific block height has been committed. This is very similar to the mechanism we have now in the block persistence.

2. The reason for this change is that the acceptance test needs to be changed. Instead of waiting in the acceptance until **block** persistence has reached a certain block, we need to wait until **state** persistence has reached a certain block. State persistence is updated slightly after the block storage. 

3. Once you add the latch mechanism and change the acceptance test, we need to undo 2 hacks I had to do in block storage to make the current bad mechanism pass tests: (1) block storage should be fixed to update state storage AFTER it writes to its own persistence layer. (2) the tests for block storage (`does not update last committed block height and timestamp when persistence storage fails`) should be changed back to make sure state storage is not updated if block persistence fails.

**Comment by talkol** [comment]
FYI @erankirsh @electricmonk this is an integration issue

**Comment by electricmonk** [comment]
what do you mean integration issue?

**Comment by noambergIL** [comment]
First 1+2 done in pull #72

**Comment by ronnno** [comment]
latch should be working now after PR #92 was merged

**Comment by talkol** [comment]
Second 1+2+3 done in https://github.com/orbs-network/orbs-network-go/pull/107/commits/1520b2b96f40d3da34a682e6c7001d36f3f33690
