### ISSUE TITLE
introduce file based config system

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#74]
Func `NewNode()` in node.go:29 has too many parameters and this will get worse unless an alternative mechanism for passing config is found. 
This is relevant to prod and tests.
See @electricmonk's comment on #73.
@talkol

**Comment by electricmonk** [comment]
Requirements:
- every service defines its config (like today, using an interface)
- allow setting bare minimum of config for component tests
- config should be versioned by block height (V1.2)
- maybe implement by code generation (V1.1)
- config system should support rich golang types (e.g. `time.Duration`) - reading from file will automatically translate. This means setting a standard for all duration prop keys in config (for instance suffixed with `_in_millis`).
- retain config factory methods `ForAcceptanceTests` / `ForProduction`
- main() should take a mandatory arg defining path to config

**Comment by yonidavidson** [comment]
You can change the NewNode(params) to a struct NodeConfig.
And create multiple "constructors"
NewNodeConfig(...regular params such as new Node )
NewNodeConfigFromFile("file_name").
NewNodeConfigFromEnviroment()
