### ISSUE TITLE
return `added` from BlockPersistence.WriteNextBlock()

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#742]
Currently `BlockPersistence.WriteNextBlock()` does not return an error if asked to write a block height that is already committed. Instead it does nothing. The reason is that it's a common race condition between consensus and node-sync. The race condition is detectable only in the adapter and it should not stop the calling flow. 

Node sync and consensus may both introduce blocks which have already been committed. 

But in case the current height is already later, the adapter does not communicate back in any way that `BlockPersistence.WriteNextBlock()`  did nothing. 

Suggest: adding a success boolean to `BlockPersistence.WriteNextBlock()` interface.

benefits:
-  simplify `tamperingBlockPersistence.notifyChanFor()` because we would be able to avoid calling `tamperingBlockPersistence.advertiseAllTransactions()` more than once per block. 
- `BlockPersistence` API more expressive and easy to understand.

**Comment by electricmonk** [comment]
@ronnno this is done, right? if so, please close the issue
