### ISSUE TITLE
CI step of ASB is running from within Orbs Network Go's CI 

### ISSUE THREAD

**Issue by itamararjuan** [orbs-network/orbs-network-go#833]
in my opinion, this sounds problematic and also causes the build of this repo to become longer to run
and will cause a classic death by a thousand cuts for this repo's run time which is already long.

Let's talk about this and see what can be done to improve this and make this run AFTER
this repo has finished running it's tests correctly.

In my eyes also flakiness tests are supposed to be run on a different level and be more of an introspection tool rather than a condition for the repo's build success.

**Comment by electricmonk** [comment]
ASB is dead for now, closing
