### ISSUE TITLE
Potential sync issue between ScanBlocks() and WaitForBlock()

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#837]
The test `TestSendSameTransactionFastTwiceToSameNode` when running with Lean Helix sometimes fails on `requireTxCommittedOnce()` on the line:
```
require.Len(t, blocks, int(height), "ScanBlocks should return %d blocks, instead got %d", height, len(blocks))
```

This could happen because WaitForBlock() returns with latest block but ScanBlocks() is not yet updated.
This does not seem possibly because `WriteNextBlock()` is protected with a `Lock()` and ScanBlocks is protected with `RLock()`

**Comment by electricmonk** [comment]
@IdoZilberberg please follow up - is this a real issue? please either close or assign for work in Q32019
