### ISSUE TITLE
Add reporting to consensus context

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#87]
heads up, I added a printf to help me debug acceptance in my latest PR:

https://github.com/orbs-network/orbs-network-go/blob/feature/virtual-machine-finish/services/consensuscontext/service.go#L42

once it's approved, please convert the printf to `reporting.Info`

**Comment by IdoZilberberg** [comment]
Done, opened https://github.com/orbs-network/orbs-network-go/pull/103

**Comment by IdoZilberberg** [comment]
Merged to master
