### ISSUE TITLE
Stability network issues

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#966]
- [ ] Block Sync: 99% of availability requests don't get availability responses. Probably t/o is too low.
- [ ] Block Sync (server): new metric: millis to return availability responses + block-sync responses.
- [ ] Virtual Machine: histogram: ProcessTransactionSet

- [ ] New Dashboard: add graphs of tx/sec of TransactionPendingPool.incomingTransactions & ConsensusContext.incomingTransactionsToBlock

- [ ] Client modifications: variable rate: 0 tx/s (empty blocks), low rate, high rate (500 tx burst / 60s)
Preferably alternate between states somewhat gradually, not sharply - consult with Tal
- [x] New metric: measure incoming TCP messages (direct_incoming.go)
- [ ] direct_incoming.go - serverHandleIncomingConnection() change error from Info() to Error()
- [x] New metric per TCP connection: rate of gossip messages.

**Comment by electricmonk** [comment]
@IdoZilberberg did any of these happen?

**Comment by IdoZilberberg** [comment]
@electricmonk added a comment to https://orbs-network.monday.com/boards/269852950/pulses/313028609 to look in this issue for ideas on what to monitor. 
Some items on the above list are monitored in the production dashboard already.

**Comment by IdoZilberberg** [comment]
I suggest closing this issue, it is stale.
