### ISSUE TITLE
No clear metrics/error when fails to create connection or send gossip message to another node

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#971]
We disabled one of the nodes by changing its IP, and this did not show up in metrics errors.
* Node IP was changed to 10.0.0.0 (invalid IP)
* Other nodes are valid
* The invalid node is able to send requests to other nodes (e.g. block sync availability request) but other nodes cannot send back (e.g. block sync availability response).

Needs clear log / metric so going forward this will be easily identifiable (as this will happen in production of course)

**Comment by electricmonk** [comment]
@IdoZilberberg is this fixed now to your satisfaction?
