### ISSUE TITLE
Cancel context on lean helix service when view terminates

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#994]
Every lean helix view should have its own dedicated context

* The view timeout (election trigger) should cancel the context

* If someone external cancels the view, for example a block arriving during sync (update state), the view context should be canceled as well

This will prevent functions like GetTransactionsForOrdering that block for a long time (9 seconds if no traffic) from blocking the main consensus goroutine

**Comment by electricmonk** [comment]
@IdoZilberberg this relates to what we discussed with a context per tick
